### ISSUE TITLE
You stumbled upon a bug in vite-plugin-ssr's source code

### ISSUE THREAD

**Issue by un1tT** [vikejs/vike#1099]
### Description

I'm facing this issue on page mount (in the `onMount` method of SolidJS). What's interesting - it happens only in incognito mode.
Here is the error log from the browser console:

``Error: [vite-plugin-ssr@0.4.117][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at D (chunk-992137b2.js:1:309)
    at r (chunk-992137b2.js:2:1927)
    at Mt (chunk-992137b2.js:2:23143)
    at tn (chunk-0ec6ca4d.js:2:5872)
    at en (chunk-0ec6ca4d.js:2:5788)
    at o (chunk-0ec6ca4d.js:2:11496)``

**Comment by un1tT** [comment]
@brillout I'm not sure where the `assert()` function you are looking for is. Here is the stack trace that I see in the error: 
![image](https://github.com/brillout/vite-plugin-ssr/assets/29070505/d1cb9afa-d8cf-4292-b367-42e7a21481f9)

This is the production build of the app. For some reason, the issue is not reproducible in the dev mode. Thanks for your help.

**Comment by brillout** [comment]
Click on the chunk links, you'll get to an `assert()` call at some point.

Alternatively, reproduction welcome (doesn't need to be minimal).

Actually, before anything, update to the latest version.

**Comment by brillout** [comment]
I'll re-open once I can get my hands on an actionable.
