### ISSUE TITLE
Vercel regression

### ISSUE THREAD

**Issue by fromtheghost** [vikejs/vike#1158]
### Description

Hi - thanks for the great plugin. I'm working with the latest build and trying to deploy to Vercel. I've used it for a year without issue, but now Vercel is giving this error:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/vike/dist/esm/node/runtime/index.js' imported from /var/task/api/ssr.js
Did you mean to import vike/dist/cjs/node/runtime/index.js?
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:329:11)
    at moduleResolve (node:internal/modules/esm/resolve:992:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:936:12)
    at defaultResolve (node:internal/modules/esm/resolve:1178:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

My /api/ssr.js file looks like this:

```
import { renderPage } from "vike/server";

export default async function handler(req, res) {
	const pageContextInit = { urlOriginal: req.url };
	const pageContext = await renderPage(pageContextInit);
	const { httpResponse } = pageContext;
	console.log("requesting URL: ", req.url);

	if (!httpResponse) {
		res.statusCode = 200;
		res.end();
		return;
	}

	const { body, statusCode, headers } = httpResponse;
	res.statusCode = statusCode;
	headers.forEach(([name, value]) => res.setHeader(name, value));
	res.end(body);
}
``` 

It may be worth noting that in ./server.js I see this line:

`export * from './dist/esm/node/runtime/index.mjs'`

But that file does not seem to exist in my folder structure:

![Capture](https://github.com/vikejs/vike/assets/108136147/459d2088-573e-4065-81f0-73019af9ed6e)

**Comment by brillout** [comment]
Indeed, there seem to be a regression on Vercel's part: re-deploying the exact same commit that used to work is now failing.

Do you mind doing some Googling about it? There must be a *lot* of people complaining about it, as it doesn't seem to be Vike specific: the error in my case is about Vue not being able to be resolved.

Keep me updated. I can PM some Vercel folks.

**Comment by fromtheghost** [comment]
OK - I wasn't sure if this was a Vercel or Vike issue. I opened a ticket with them last Thursday but haven't received a reply, and couldn't find anyone else experiencing the issue.

**Comment by fromtheghost** [comment]
Might be related to this: https://github.com/orgs/vercel/discussions/4231

**Comment by brillout** [comment]
Have you tried the workaround posted there?

**Comment by fromtheghost** [comment]
Yes - I haven't gotten it to work though.

**Comment by brillout** [comment]
👍 Closing in favor of https://github.com/orgs/vercel/discussions/4231.

Aslo, FYI `vite-plugin-vercel` still works, see this Vike app using vite-plugin-vercel successfully deployed: https://github.com/brillout/vike_vite-plugin-vercel (https://vike-vite-plugin-vercel.vercel.app/).

**Comment by brillout** [comment]
Everything [works again](https://github.com/orgs/vercel/discussions/4231). I could successfully re-deploy https://github.com/brillout/vike-with-vercel.
