### ISSUE TITLE
Improve v1 page config errors

### ISSUE THREAD

**Issue by ruigouveiamaciel** [vikejs/vike#1159]
### Description

# Issue & Enhancement

Currently, if someone writes the following header file, it will fail silently. The page will still work and render properly but the title will be undefined.

```ts
// src/pages/_error/+config.h.ts
import { Config, PageContext } from "../../renderer/types.ts";

export default {
  title: ({ is404 }: PageContext) => is404 ? "Page not found" : "Internal Server Error",
} satisfies Config;
```

Ideally there should be a warning / error message explaining why you can't directly define functions in the header files.

# Working Example

```ts
// src/pages/_error/title.ts
import { Config, PageContext } from "../../renderer/types.ts";

export default function title({ is404 }: PageContext) {
    return is404 ? "Page not found" : "Internal Server Error";
}
```
```ts
// src/pages/_error/+config.h.ts
import { Config, PageContext } from "../../renderer/types.ts";
import title from "./title";

export default {
  title: title,
} satisfies Config;
```

**Comment by AurelienLourot** [comment]
It's true that although I have read [the doc about it](https://vike.dev/header-file), for some reason I would have bet that this would work, not sure why:
https://github.com/vikejs/vike/tree/aurelien/reproducer-issue-1159
https://github.com/vikejs/vike/commit/83126f13

I'm also wondering if there is a way to detect this and fail at build time.

**Comment by brillout** [comment]
> Ideally there should be a warning / error message explaining why you can't directly define functions in the header files.

Agreed and I consider this a bug. I'll have a look at it.

**Comment by brillout** [comment]
@AurelienLourot There is a little explanation at https://vike.dev/header-file#why but I'm thinking we may want to elaborate it and show it more prominently 🤔. I think the idea of the explanation is good but it just needs a little bit of polishing.

**Comment by brillout** [comment]
Both situations now lead to a helpful error message.

Thanks for creating this ticket, let us know if you stumble upon any other such paper cut. (I don't need a reproductoin anymore).
