### ISSUE TITLE
Remove ssr.external settings for "vike" and "vike/server" ?

### ISSUE THREAD

**Issue by thomasjm** [vikejs/vike#1163]
### Description

The comment in the relevant code indicates it could be removed once Vike is published in ESM, which seems to be the case now.

This setting is currently standing in the way of me creating a standalone server build by non-externalizing everything that's needed in my `server/index.ts` file. I had to write a mini Vite plugin to remove the setting as a workaround.

https://github.com/vikejs/vike/blob/5095cd97576eccadd2345512a356da8c76a315a2/vike/node/plugin/plugins/commonConfig.ts#L22-L24

This comment gives more context on what I'm trying to do: https://github.com/cyco130/vavite/issues/24#issuecomment-1749893296

**Comment by brillout** [comment]
Done; thanks for reaching out.
