### ISSUE TITLE
bug in vite-plugin-ssr's source code.

### ISSUE THREAD

**Issue by shivaniTechM1993** [vikejs/vike#1164]
### Description

Uncaught (in promise) Error: [vite-plugin-ssr@0.4.112][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.

    at getPageContextSerializedInHtml.js?v=8c1f2c63:38:9

    at Array.map (<anonymous>)

    at getPageContextsSerializedInHtml (getPageContextSerializedInHtml.js?v=8c1f2c63:36:41)

    at getPageContexts (getPageContext.js?v=8c1f2c63:20:26)

    at hydrate (entry.js:15:40)

    at entry.js:9:1

**Comment by brillout** [comment]
Update to the latest version. I'll re-open if you still stumble upon the issue.
