### ISSUE TITLE
error: dev (potential hmr?) error.

### ISSUE THREAD

**Issue by jaymanmdev** [vikejs/vike#1168]
### Description

```
error: The server is being restarted or closed. Request is outdated
 code: "ERR_CLOSED_SERVER"
```

I cannot quite remember how I managed to get the error, but it seems like it is using a stale Request of some kind? It might have happened after saving a file and triggering HMR with Vite.

**Comment by brillout** [comment]
https://brillout.github.io/rules/

**Comment by jaymanmdev** [comment]
> https://brillout.github.io/rules/

I apologise for this. Everything seems to be working fine now. It was just a one off occurrence I think.

I will keep these rules in mind for the next time I submit an issue in relation to Vike.

Thanks heaps!

**Comment by brillout** [comment]
Thanks 👍
