### ISSUE TITLE
Cannot convert undefined or null to object when `onBeforeRender` hook has no return

### ISSUE THREAD

**Issue by chrisvander** [vikejs/vike#1179]
### Description

Got the following error when I clicked on a page that client-side rendered in. 

```
TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyDescriptors (<anonymous>)
    at objectAssign (objectAssign.js?v=9689845f:6:41)
    at executeOnBeforeRenderHookClientSide (getPageContext.js?v=9689845f:140:5)
    at async getPageContextAlreadyRouted (getPageContext.js?v=9689845f:116:37)
    at async getPageContextUponNavigation (getPageContext.js?v=9689845f:69:39)
    at async getPageContext (getPageContext.js?v=9689845f:31:37)
    at async fetchAndRender (useClientRouter.js?v=9689845f:137:35)
```

The error was thrown because the `onBeforeRender` hook did not have a return value, since I was just calling a function that operates on the `PageContext`:

```ts
export async function onBeforeRender({ trpc }: PageContext) {
  await trpc?.participant.list.prefetch({ withIdentifiable: true })
  // had to add the following
  return { pageContext: {} }
}
```

Side tangent: this is a lovely pattern for tRPC and a proper example of this would have been great when I first put this together. I create some tRPC server-side helpers, pass it into the context (undefined on client), use that in some isomorphic `onBeforeRender` hooks (which only functions in SSR), and later on dehydrate the state and pass it with `pageContext` to the client:

```ts
async function render(pageContext: PageContextServer) {
  const { Page, pageProps } = pageContext

  // dehydrate any tRPC calls in onBeforeRender()
  pageContext.dehydratedQueryState = pageContext.trpc?.dehydrate()

  // ...rest of function
}
```

**Comment by brillout** [comment]
Thanks for opening the bug report &mdash; fix pre-released as `vike@0.4.143-commit-f03b42d`.

> lovely pattern for tRPC 

That does ineeded sound neat. Would you be up for putting together a little example? We could then add it to https://vike.dev/tRPC for others to benefit. (And I'm curious about it as well.)

**Comment by chrisvander** [comment]
Yeah, would be happy to. I'll figure out the best way to showcase. Would you prefer things stick to the V1 design?

Related to this discussion - when a client-side navigation occurs and the `index.pageContext.json` is fetched, is there a way to trigger my isomorphic `onBeforeRender` hook in `*.page.tsx` server-side? That pattern doesn't appear to be happening, and it may be better to populate `dehydratedQueryState` server-side in one request rather than client-side.

**Comment by brillout** [comment]
> Yeah, would be happy to.

👍 Looking forward to it.

> Would you prefer things stick to the V1 design?

Yea that'd be great as it's soon going to be the only supported design.

> Related to this discussion - when a client-side navigation occurs and the `index.pageContext.json` is fetched, is there a way to trigger my isomorphic `onBeforeRender` hook in `*.page.tsx` server-side? That pattern doesn't appear to be happening, and it may be better to populate `dehydratedQueryState` server-side in one request rather than client-side.

Why not making it server only? You can toggle this on a page-by-page basis.

Btw. I probably told you this already in the past, but in case your company is up for it: https://github.com/sponsors/brillout.

**Comment by chrisvander** [comment]
I was trying to avoid multiple files. I'll give it a go.

Do you have a guide on transitioning to the V1 design?

(Also, sponsored 😀)

**Comment by brillout** [comment]
[I've seen](https://twitter.com/vike_js/status/1714260263812178047) 🙂. Thanks a lot 💚.

Yes: https://vike.dev/migration/v1-design. Feel free to let me know if you stumble upon any issues while migrating.

The V1 design is already quite stable: there is only a minor breaking change (which is trivial to apply) coming before its stable release.
