### ISSUE TITLE
`dist/foo/bar.page.js` files unrelated to Vike cause `vite build` to fail

### ISSUE THREAD

**Issue by AurelienLourot** [vikejs/vike#1189]
### Description

`pnpm run build --emptyOutDir` calls `vite build --emptyOutDir` in the examples, which should allow us to perform a clean build, however the `--emptyOutDir` option seems to have no effect.

I suspect the problem to be here: https://github.com/vikejs/vike/blob/main/vike/node/plugin/shared/isViteCliCall.ts

**Comment by AurelienLourot** [comment]
Actually, it kind of works already and `outDir` gets emptied as expected, however when setting an `outDir` in an example (as in https://github.com/vikejs/vike/blob/main/examples/react-full-v1/vite.config.ts#L10 where we set it to `dist/nested/`), we seem to manipulate `outDir` to e.g. `dist/nested/client/` in https://github.com/vikejs/vike/blob/main/vike/utils/getOutDirs.ts before passing it to Vite.

So Vite ends up emptying `dist/nested/client/` but technically not the full `dist/nested/`. Instinctively I think this should still be good enough but a user on Discord reported a concrete problem around that so I'll ask them to post a reproducer here and I'll then re-open.

**Comment by robinelvin** [comment]
The Vite build only empties/removes `dist` and `client` directories in `dist`. Any extra directories are left intact which isn't a problem in itself as other build outputs may produce different artifacts. However the problem arises if these other directories exist in `dist` containing files with the word "page" in their name and with content that will produce an error.

Steps to reproduce:

1. Use `examples/react` from this repo
2. `yarn install` or `npm install`
3. Run `yarn build` or `npm build`
4. Observe successful build
5. `mkdir dist/stuff`
6. `echo "import 'foo'" > dist/stuff/index.page.js`
7. `yarn build` or `npm build`
8. Build now fails

**Comment by AurelienLourot** [comment]
@robinelvin thanks a lot. It sounds like a bug on our side. It sounds like manipulating `outDir` isn't a safe thing to do and I'm going to have a look and see if this can be done differently.

Out of curiosity: how did you stumble into this? Did you have at first a vite plugin that was writing files in `dist/`, which you then removed from your setup and the files lingered? Which plugin was it?

**Comment by robinelvin** [comment]
In my build I have some output from Typescript compilation which ends up in a directory in `dist`. This is the Express server which is essentially the same as [boilerplates/boilerplate-react-ts](https://github.com/vikejs/vike/tree/main/boilerplates/boilerplate-react-ts) but compiled rather than using `ts-node` which reduces start-up time.

**Comment by AurelienLourot** [comment]
Ah ok but it is not generated by `vite build`, correct? I'm looking for a real-life case in which `vite build` wouldn't be able to clean after itself. I'm wondering if such a case exists.

**Comment by robinelvin** [comment]
My point is that `vite build` shouldn't be looking in `dist` for files. As far as I am aware it cleans its own outputs correctly so the original bug description isn't right.

**Comment by AurelienLourot** [comment]
Oh I see, thanks, does that ring a bell @brillout ? TL;DR: the bug description is wrong. This is about `dist/something-different-from-client-or-server/something.page.js` being somehow picked up by Vite, although this seems to be outside Vite's `outDir`, which we manipulate to be `dist/client/`.

**Comment by brillout** [comment]
> This is about `dist/something-different-from-client-or-server/something.page.js` being somehow picked up by Vite, although this seems to be outside Vite's `outDir`, which we manipulate to be `dist/client/`.

Vike should use [`fast-glob`](https://www.npmjs.com/package/fast-glob) in a way that skips `dist/`, but that isn't possible because Vike uses `fast-glob` *before* Vite resolves `vite.config.js`. This means Vike cannot know the `config.build.outDir` value when using `fast-glob`.

**Comment by AurelienLourot** [comment]
Thanks for the useful pointer! Actually `fast-glob` is called by `findPageFiles()` which ends up being called at two places:

1. `buildConfig.ts` / `configResolved`, which is by definition at a spot where `outDir` has been resolved, since we tweak it just before (we add `client/`) in the `config` hook in the same file
2. `determineOptimizeDeps()`, called by `devConfig.ts` / `configResolved`. The `devConfig` "sub-plugin" runs just before the `buildConfig` one, so we haven't tweaked `outDir` yet at this point, but still I would expect the original value to be available right there.

So I feel like at both places it should be possible to pass some `outDir` to be ignored in `findPageFiles()`. Let me play with that and create a PR if I succeed.

**Comment by brillout** [comment]
@AurelienLourot 👍

**Comment by brillout** [comment]
Fixed.

**Comment by AurelienLourot** [comment]
The very last commits to #1192 actually have re-broken it. Having a look

**Comment by AurelienLourot** [comment]
Fixed
