### ISSUE TITLE
Dist file generated in workspace, makes dist unusable

### ISSUE THREAD

**Issue by rossanmol** [vikejs/vike#1204]
### Description

There is this bug inside `importBuild.cjs` which is generated automatically here: 
 [   `  const { setImportBuildGetters } = await import('${importPath}');`,](https://github.com/vikejs/vike/blob/926313b298dbffac434ab52a44be7b24c1d16d7b/vike/node/plugin/plugins/importBuild/index.ts#L42)

In NPM workspace, `node_modules/vike` is located under root directory of the whole monorepo, which causes something of this sort:
```
const { setImportBuildGetters } = await import('../../../../node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js');
```

Instead of resolving the location during build time, this could be modified as follows:

```
const loc = require.resolve("vike");
const basePath  = loc.split("node_modules/vike")[0];
const { setImportBuildGetters } = await import(`${basePath}node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js`);
```

Or even better, `loadImportBuild.js` could be added to exports in package.json so that it can simply be imported like so:
```
const loc = require.resolve("vike");
const basePath  = loc.split("node_modules/vike")[0];
const { setImportBuildGetters } = await import('vike/dist/esm/node/runtime/globalContext/loadImportBuild.js');
```

For now, I am manually updating `importBuild.cjs`, as otherwise the import is just invalid when `dist` is deployed without the rest of the monorepo.

**Comment by brillout** [comment]
You aren't supposed to move `node_modules/` into your production environement (e.g. `$ rsync node_modules/ user@remote:/node_modules`), instead you're supposed to run `$ pnpm install` and then `$ pnpm run build` in your production environment. The path in `importBuild.cjs` will then be correct.

I undertand this is very limiting (which I find unacceptable) and I'll be working on https://github.com/vikejs/vike/issues/562 and https://github.com/vikejs/vike/issues/1165 (which will solve the issue) right after the V1 design is out-of-beta.

Closing in favor of https://github.com/vikejs/vike/issues/562.

Until #526 is implemented I guess you can continue using your workaround?
