### ISSUE TITLE
0.4.144 Route string defined in config.h.ts does not work

### ISSUE THREAD

**Issue by dajinchu** [vikejs/vike#1208]
### Description

Setting route string in `+config.h.ts` does not take precedence over file system routing, whereas setting in `+route.ts` does. Which is right?

reproduction:
https://github.com/vikejs/vike/compare/main...dajinchu:vite-plugin-ssr:dc/route-string-config?expand=1

**Comment by brillout** [comment]
👍 Let me have a look

**Comment by brillout** [comment]
Pre-released in `0.4.144-commit-e40e9b1`.

**Comment by dajinchu** [comment]
Thanks!!!
