### ISSUE TITLE
vike resolves pages from another vike app (global state pollution?)

### ISSUE THREAD

**Issue by samuelstroschein** [vikejs/vike#1212]
### Description

Follow up of https://github.com/vikejs/vike/discussions/1202#discussioncomment-7381287

## Problem 

Running multiple instances of vike in a monorepo/same server leads to routing issues. Vike matches routes/pages from another instance. 

![CleanShot 2023-10-25 at 15 30 48@2x](https://github.com/vikejs/vike/assets/35429197/e50acffd-bce2-45bb-87fe-92c411bc2fa4)

## Reproduction 

1. Clone https://github.com/samuelstroschein/stackblitz-starters-fd54nc
2. Run `npm i && npm run build && npm run start`
3. Open `localhost:3000`
4. Click on `go to /editor/login`

The server will log `editor router page ids [ '/pages/index' ]` which is a bug. The route `index` does not exist for the editor package, only for the website package. 

The wrong page ids lead vike's `renderPage` middleware in `editor/router.ts` to return a 404. The website `renderPage` middleware in `website/router.ts` is subsequently triggered, also returning a 404 because no `editor/login` page exists in the website package. 

The result is a bug that no page is rendered for `/editor/login` even though the route exists. 

## Additional information 

- Using domain-driven settings does not resolve the bug. Vike matches incorrect pages. 
- I suspect that vike stores stuff in the node_modules/the runtime, leading to global state pollution. If so, I encourage vike to compile all required state into the dist output.
- Having multiple vite apps in one repo is a basic monorepo requirement.

**Comment by brillout** [comment]
You're running two Vite apps within the same Node.js process &mdash; that won't work. Not only won't it work with Vike, but I also expect Vite to fail with such setup.

If you want two separate apps, then create two seperate processes i.e. two separate Express.js server.

**Comment by samuelstroschein** [comment]
We are not running Vite. Vite only builds the project?

**Comment by AurelienLourot** [comment]
@brillout I think it's the page file globs

**Comment by brillout** [comment]
> We are not running Vite. Vite only builds the project? The express server uses the vike (build) middleware

I see. Still: having two different Vike apps in a single Node.js process is problematic for many reasons. (Technically speaking: Vike's server runtime assumes that there is only one Vike app.)

**Comment by brillout** [comment]
> I think it's the page file globs

The globbing is only done in dev.

**Comment by AurelienLourot** [comment]
Yes but what's being globbed at build time will then be run in prod, and so may lead to rogue routes in prod. I'm surprised you're able to rule this out so quickly to be honest.

**Comment by brillout** [comment]
> Yes but what's being globbed at build time will then be run in prod, and so may lead to rogue routes in prod. 

Agreed. And, in general, Vike's server runtime uses a *lot* of global variables (see all the `getGlobalObject()` usages, in particular in `node/runtime/globalContext.ts` which would actually include the rogue routes you mentioned). Supporting mutliple apps within the same Node.js process would be a major undertaking. I doubt any frontend framework out there supports that.

**Comment by samuelstroschein** [comment]
We are going to separate the servers. 

One server/process was so beautifully simple that it might be worth an exploration. We had 0 deployment burdens, just write a router and be done. It felt like "the serverless stack" but we had a full server without limitations. 

In any case, Vike's docs should be updated. The slogan "Vike is just a middleware" misled us to believe that Vike works out of the box with what we have in mind. After all, the use case for express.router is exactly what we are doing: 

> Use the express.Router class to create modular, mountable route handlers. A Router instance is a complete middleware and routing system; for this reason, it is often referred to as a “mini-app”.

---

> Vike's server runtime uses a lot of global variables (see all the getGlobalObject() usages, in particular in node/runtime/globalContext.ts

Why does vike even have a runtime? Compile the output, including the `renderPage` function into dist and call it a day. That would likely already resolve this issue as global variables between different vike instances wouldn't be shared.

**Comment by AurelienLourot** [comment]
Sorry, just read the issue title. I stand corrected

**Comment by samuelstroschein** [comment]
@AurelienLourot same process. basically we want domain-driven development but a separate package.json to unbundle dependencies

**Comment by brillout** [comment]
> Why

Let alone the fact that there are two different `dist/` directories is a major problem. I could probably create an impressive list of issues about having 2 Vike apps for 1 server (i.e. 1 Node.js process). Again, I don't think any frontend framework out there supports that, for good reasons.

@AurelienLourot I actually edited the title :)
