### ISSUE TITLE
Build Error Occurs Due to Environment Variable Declaration Order

### ISSUE THREAD

**Issue by RoyMcCrain** [vikejs/vike#1214]
### Description

https://stackblitz.com/edit/vitejs-vite-tzuwdf?file=.env

Environment variables were set.
```sh
PUBLIC_ENV__MOCK=true
PUBLIC_ENV__MOCK_URL=http://localhost:3000
```

Defining in this order results in a build error when using import.meta.env.PUBLIC_ENV__MOCK_URL.
However, swapping the order allows the build to succeed.

**Comment by brillout** [comment]
Fix pre-released in `0.4.144-commit-756f5d7`.

Btw, would your company be up for [sponsoring](https://github.com/sponsors/brillout)? It makes a big difference.

**Comment by RoyMcCrain** [comment]
@brillout 
Certainly, I will discuss the sponsorship opportunity with my company. It would be more convenient for us to become a sponsor if contributions can be made through Open Collective.

**Comment by brillout** [comment]
Thanks 💚 sponsors make a *big* difference. (I also saw your one-time donation 🙂)

> more convenient [...] through Open Collective

👍 Keep me updated about your discussion; I'll then create an Open Collective once things are confirmed.

Thank you Roy.
