### ISSUE TITLE
Unable to collect styled-component styleTags for SSR.

### ISSUE THREAD

**Issue by der1igedon** [vikejs/vike#1217]
### Description

Hello,

I use vike with grommet.io components. These are styled by styled-components. I try to collect the styleTags of the pages in order to use them for server-side-rendering with client hydration. I use ServerStyleSheet() as described here and in the vike docs:

https://styled-components.com/docs/advanced#server-side-rendering

The problem is, that there are no styles collected with grommet components used. If I use other components and apply styled-components to it, it works just fine. I setup a simple example:

https://github.com/der1igedon/vite-ssr-styled-components-grommet/tree/main/

The styles should be collected on the server side (see renderer/_default.page.server.tsx) and injected in the <style>-Tag of the documentHtml. Unfortunately there are no styles detected. See
  console.log("Found styles: ", sheet.getStyleTags());

Can anyone tell me how this can be achieved?
Thank you!

**Comment by AurelienLourot** [comment]
Hey @der1igedon, thanks for reaching out. I have wrapped my head around styled-components and grommet, and am now having a look at your repo

**Comment by AurelienLourot** [comment]
See my fix in https://github.com/der1igedon/vite-ssr-styled-components-grommet/pull/1

Please note also that you are using an old version of Vike, so you might run into other issues later on. The latest version is 0.4.144
