### ISSUE TITLE
fileSystemRoutingRoot breaks 404 behavior

### ISSUE THREAD

**Issue by dajinchu** [vikejs/vike#1219]
### Description

```
Error: [vike@0.4.144][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at file:///Users/dajinchu/Alignable/vite-plugin-ssr/vike/dist/esm/node/runtime/renderPage/log404/index.js:81:9
    at Array.forEach (<anonymous>)
    at getPagesAndRoutesInfo (file:///Users/dajinchu/Alignable/vite-plugin-ssr/vike/dist/esm/node/runtime/renderPage/log404/index.js:73:18)
    at log404 (file:///Users/dajinchu/Alignable/vite-plugin-ssr/vike/dist/esm/node/runtime/renderPage/log404/index.js:18:13)
    at renderPageAlreadyPrepared (file:///Users/dajinchu/Alignable/vite-plugin-ssr/vike/dist/esm/node/runtime/renderPage.js:128:15)
    at renderPageAndPrepare (file:///Users/dajinchu/Alignable/vite-plugin-ssr/vike/dist/esm/node/runtime/renderPage.js:93:12)
    at file:///Users/dajinchu/Alignable/vite-plugin-ssr/vike/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///Users/dajinchu/Alignable/vite-plugin-ssr/vike/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///Users/dajinchu/Alignable/vite-plugin-ssr/vike/dist/esm/node/plugin/shared/addSsrMiddleware.js:18:27
```

When `filesystemRoutingRoot` is specified, 404s throw the above error instead of rendering the error page. This breaks [bifrost](https://github.com/Alignable/bifrost) as we rely on is404 to detect if no route matched and proxy to legacy backend.

Reproduction: https://github.com/dajinchu/vite-plugin-ssr/compare/main...dc%2Frepro-fsrouting-404?body=&expand=1

**Comment by brillout** [comment]
👍 Let me have a look.

**Comment by brillout** [comment]
I see what's going on, let me fix it.

**Comment by brillout** [comment]
Fix pre-released as `0.4.144-commit-6aef8a6`.

**Comment by brillout** [comment]
> [bifrost](https://github.com/Alignable/bifrost)

💯 I've added a link to it at https://vike.dev/ruby-on-rails. (But let me know if you'd rather keep it private.)

**Comment by dajinchu** [comment]
its not exactly using RoR as a "server" - we're still running on fastify, just proxying some routes to rails and handling turbolinks compatibility. Maybe it goes in "other"

Probably need to write a better README at some point 😅

**Comment by brillout** [comment]
I'm thinking RoR users may want to know about it and search for "Ruby on Rails" on Vike's docs 🤔. Maybe "backend" would be more fitting than "server".

> Probably need to write a better README at some point 😅

It's probably fine for now :)
