### ISSUE TITLE
Can't build on vercel, the log told me to create a bug report here

### ISSUE THREAD

**Issue by pencilcheck** [vikejs/vike#1233]
### Description

Error: [vike@0.4.144][Bug] You stumbled upon a bug in Vike's source code. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours). Debug info (for Vike maintainers; you can ignore this): /pages/about/index.page.tsx
--
00:39:15.105 | at assertExportNames (file:///vercel/path0/node_modules/.pnpm/vike@0.4.144_react-streaming@0.3.15_vite@4.5.0/node_modules/vike/dist/esm/node/prerender/runPrerender.js:140:5)
00:39:15.105 | at Array.forEach (<anonymous>)
00:39:15.105 | at runPrerender (file:///vercel/path0/node_modules/.pnpm/vike@0.4.144_react-streaming@0.3.15_vite@4.5.0/node_modules/vike/dist/esm/node/prerender/runPrerender.js:61:32)
00:39:15.105 | at prerenderFromAPI (file:///vercel/path0/node_modules/.pnpm/vike@0.4.144_react-streaming@0.3.15_vite@4.5.0/node_modules/vike/dist/esm/node/prerender/runPrerender.js:28:5)
00:39:15.105 | at prerender (file:///vercel/path0/node_modules/.pnpm/@vite-plugin-vercel+vike@2.0.0_vike@0.4.144_vite-plugin-vercel@2.0.0_vite@4.5.0/node_modules/@vite-plugin-vercel/vike/dist/vike.js:96:3)
00:39:15.106 | at Object.writeBundle (file:///vercel/path0/node_modules/.pnpm/vite-plugin-vercel@2.0.0_@vite-plugin-vercel+vike@2.0.0_vike@0.4.144_vite@4.5.0/node_modules/vite-plugin-vercel/dist/index.js:648:25)
00:39:15.106 | at async Promise.all (index 4)
00:39:15.106 | at PluginDriver.hookParallel (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25472:9)
00:39:15.106 | at file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:26792:13
00:39:15.106 | at catchUnfinishedHookActions (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
00:39:15.106 | at build (file:///vercel/path0/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.9/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48085:22)
00:39:15.106 | at triggerFullBuild (file:///vercel/path0/node_modules/.pnpm/vike@0.4.144_react-streaming@0.3.15_vite@4.5.0/node_modules/vike/dist/esm/node/plugin/plugins/autoFullBuild.js:72:5)
00:39:15.106 | at Object.handler (file:///vercel/path0/node_modules/.pnpm/vike@0.4.144_react-streaming@0.3.15_vite@4.5.0/node_modules/vike/dist/esm/node/plugin/plugins/autoFullBuild.js:29:25)
00:39:15.106 | at async Promise.all (index 0)
00:39:15.106 | at PluginDriver.hookParallel (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25472:9)
00:39:15.106 | at file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:26792:13
00:39:15.106 | at catchUnfinishedHookActions (file:///vercel/path0/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
00:39:15.106 | at build (file:///vercel/path0/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.9/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48085:22)
00:39:15.106 | at CAC.<anonymous> (file:///vercel/path0/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.9/node_modules/vite/dist/node/cli.js:842:9) {
00:39:15.106 | code: 'PLUGIN_ERROR',
00:39:15.106 | plugin: 'vite-plugin-vercel',
00:39:15.106 | hook: 'writeBundle'
00:39:15.106 | }

**Comment by brillout** [comment]
I'll need a minimal reproduction for that one.

**Comment by pencilcheck** [comment]
https://github.com/pencilcheck/bug-vike-vercel-app

**Comment by brillout** [comment]
I need it to be minimal

**Comment by brillout** [comment]
I'll re-open if I can get my hands on a minmal reproduction.
