### ISSUE TITLE
Redirects: Support URLs with other protocols such as `mailto:` or `ipfs://`

### ISSUE THREAD

**Issue by ndavd** [vikejs/vike#1245]
### Description

Currently, redirects only support URLs of type `http`, `https` and local routes.

I propose adding support to those of type `mailto` as well.

Discussion about the topic started on https://github.com/vikejs/vike/discussions/1244.

### Motivation
- `mailto` URLs are the next more common type of emails. Some people might want to setup a certain route to a `mailto`.
- For example, in order to be easily contactable, I might setup a route in my personal website called `/mail-me` and having it redirect to my current email, as opposed to giving my email to a person (which might be a complex email prone to error when typing) I can simply give an easy to memorize link
- On top of that, `mailto` urls also support a bunch of parameters such as setting the default body and subject — which might be useful for certain use-cases, such as job applications, etc.

**Comment by brillout** [comment]
PR welcome.

**Comment by brillout** [comment]
Also:

> [Because I can think of some other types of url that might have some usecases, ipfs://, magnet: (torrents also have a lot of legitimate usecases such as distribution of Linux isos and other heavy files), etc.](https://github.com/vikejs/vike/discussions/1244#discussioncomment-7487901)

**Comment by ndavd** [comment]
Hey @brillout I actually wouldn't mind working in this myself sometime. Any hints before I dive in? What would you say is the main challenge for this?

**Comment by brillout** [comment]
The static redirections are resolved [here](https://github.com/vikejs/vike/blob/33cd9500d5fbc9290d31cb0a0c607b8b8bd8c2a6/vike/node/runtime/renderPage.ts#L491). I believe [`parseUrl()`](https://github.com/vikejs/vike/blob/33cd9500d5fbc9290d31cb0a0c607b8b8bd8c2a6/vike/utils/parseUrl.ts#L20) needs a new option `{ allowAnyProtocol?: true }`. On a high-level it's straightforward, but it's a little bit of work to set and pass the option around in a sensible way.

**Comment by ndavd** [comment]
Sounds good. Just need a way to be able to test it out in a simple project, how do you normally do it? I was going to link it locally but my project uses yarn so it's incompatible. Should I just create a pnpm project to test it or is there something like it builtin?

**Comment by brillout** [comment]
See CONTRIBUTING.md

**Comment by ndavd** [comment]
Could you elaborate more on how you would want it to be done? Should I add an `allowAnyProtocol` setting to Vike's config or can the protocol restriction be removed?

**Comment by brillout** [comment]
Figuring it out is half the fun 🙂

**Comment by usk94** [comment]
May I work on it?😀

**Comment by brillout** [comment]
Hello Yusaku, yes 💯

**Comment by ndavd** [comment]
> May I work on it?😀

Of course, in the meantime I moved on into other things, but will still also appreciate the feature
