### ISSUE TITLE
Make timeouts configurable

### ISSUE THREAD

**Issue by brillout** [vikejs/vike#1250]
### Description

E.g. enable users to increase the timeout from `4 seconds` to `30 seconds` or `Infinity`/`null`:

> [vike][Warning] The render() hook defined by /src/renderer/_default.page.client.js > `export { render }` is taking more than 4 seconds

**Comment by phonzammi** [comment]
Hi @brillout 
I've been looking & trying to solve this 'enhancement' since this morning, I have some questions, for starters:

```
meta: {
    onBeforeRender: {
      env: {
        server: true,
        timeoutWarn: 2 * 1000 // is this a good place for users to set the timeouts ?
      }
    },
```

**Comment by phonzammi** [comment]
Well, actually I did try that but I didn't create a PR yet. I don't want to be rush

I've modified a few files on my local, now I'm stuck with next question, I hope you don't mind.

how do we pass that config meta & get it at [await executeHook](https://github.com/vikejs/vike/blob/f8350d1a00c58f3118fd27797d5786bfe8c297b2/vike/node/runtime/renderPage/executeOnBeforeRenderHook.ts#L28)

for the record, i've did try and try again and try again 🤷‍♂️

**Comment by brillout** [comment]
How about `config.timeouts.{onBeforeRender,onRenderHtml,...}`? I think that woud be considerably easier to implement.

**Comment by phonzammi** [comment]
Sure, I'll try that way too
