### ISSUE TITLE
throw redirect() falsely detects infinite redirect loop

### ISSUE THREAD

**Issue by nitedani** [vikejs/vike#1270]
### Description

Reproduction: https://stackblitz.com/github/nitedani/vike-redirect-error?file=pages%2Findex%2Findex.page.jsx
Steps:
1. open in new tab
2. go to /?redirect=true -  you will be redirected to the /about page
3. go to /about?redirect=true

If I comment out `validate(graph);` in `assertNoInfiniteHttpRedirect`, it works as expected.

It would be nice If I could use the following for navigation/redirect:
```ts
import { redirect as navigateServer } from "vike/abort";
import { navigate as navigateClient } from "vike/client/router";

export const navigate = (
  url: `/${string}` | `https://${string}` | `http://${string}`
) => {
  if (import.meta.env.SSR) {
    throw navigateServer(url);
  } else {
    navigateClient(url);
    return null;
  }
};
```

**Comment by brillout** [comment]
👍 I could reproduce and it's indeed a bug.

**Comment by brillout** [comment]
Fixed, thanks for opening the bug report 👌

**Comment by nitedani** [comment]
Does this work if the redirect condition is not based on the url? For example, I would like to use my custom useProfile hook, that calls the backend(sending the session cookie), and either returns the profile or undefined.

**Comment by brillout** [comment]
Exactly, that isn't possible. That's why redirection loops are forbidden (regardless of whether they are contidional or not since Vike cannot know that).

> If no profile on dashboard, redirect to login. If profile on login, redirect to dashboard

I'm realizing that's quite a common use case, and it's quite a bummer that Vike is limiting in that regard.

I guess it's either we remove the infinite loop detection, or we limit the user 🤔

**Comment by nitedani** [comment]
I think the error should be a warning (possible redirect loop detected), shown only once.

**Comment by brillout** [comment]
An infinite loop of HTTP redirects is quite a bad outcome (overloads the server), that's why I'm inclined to make it an error in order to break the infinite loop.

**Comment by brillout** [comment]
So far no one has complained about the infinite redirect loop catcher being too strict, so I guess the solution would be to have a new setting `+doNotCatchInfiniteRedirect` if someone complains.
