### ISSUE TITLE
tauri with VPS SSG not work

### ISSUE THREAD

**Issue by algesthesiah** [vikejs/vike#1277]
### Description

You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust. Debug info (this is for the vite-plugin-ssr maintainers; you can ignore this): `{"url":"tauri://localhost"}`.

<img width="1456" alt="image" src="https://github.com/vikejs/vike/assets/26083451/f0585930-a094-43af-b45c-0aac9c255e95">

**Comment by algesthesiah** [comment]
Google and Safari is work，find this bug with tauri on Mac

**Comment by brillout** [comment]
Thanks for the bug report. I need the failing assertion: there should be an `assert()` call somewhere near the top of the stack trace.

**Comment by algesthesiah** [comment]
<img width="1109" alt="image" src="https://github.com/vikejs/vike/assets/26083451/06230ada-da1d-423c-896e-c91e1b31b135">

**Comment by brillout** [comment]
I need the `assert()` *call* (not the `assert()` implementation).

**Comment by brillout** [comment]
This is actually already fixed. Update to the latest version.

**Comment by algesthesiah** [comment]
which keyword

**Comment by brillout** [comment]
What's your browser btw.? It does a great job at prettifying the call stack.

**Comment by brillout** [comment]
You're using `0.4.48` but the latest version is `0.4.147`... you're quite far behind.

Never open a bug report with an older version. (My bad as well though: I should have checked your version before starting digging.)

**Comment by algesthesiah** [comment]
I can only use the lower version of VPS because the higher version supports esm by default and then combined with https://github.com/arco-design/arco-design this library error

SyntaxError:  Named export 'Spin' not found. The requested module '@nbit/arco' is a CommonJS module,  which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@nbit/arco';
const { Spin } = pkg;
Can you give me some help?

**Comment by algesthesiah** [comment]
> 顺便说一句，你的浏览器是什么？它在美化调用堆栈方面做得很好。

tauri  mac devtool

**Comment by brillout** [comment]
> I can only use the lower version of VPS because the higher version supports esm by default

That isn't true. There is no regression here, it's just a warning. You should be able to upgrade to `0.4.147` while still using CJS.

As for your other error, it's a ESM/CJS issue that is unrelated to Vike. Create a new GitHub Disucssion about it with a minimal reproduction.

**Comment by algesthesiah** [comment]
Thank you for your help, brother.
