### ISSUE TITLE
exports is not defined in ES module scope

### ISSUE THREAD

**Issue by algesthesiah** [vikejs/vike#1278]
### Description

vike v0.4.147 pre-rendering HTML...

(!) Experimental legacy.buildSsrCjsExternalHeuristics and ssr.format: 'cjs' are going to be removed in Vite 5.
    Find more information and give feedback at https://github.com/vitejs/vite/discussions/13816.

ReferenceError: exports is not defined in ES module scope

**Comment by algesthesiah** [comment]
vike lastest examples react-full use commonjs、ssg can find this bug

**Comment by algesthesiah** [comment]
<img width="694" alt="image" src="https://github.com/vikejs/vike/assets/26083451/bf1db0be-0d86-44ee-8c7e-c2b54021e4ea">

**Comment by brillout** [comment]
Please respect https://brillout.github.io/rules.

> (!) Experimental legacy.buildSsrCjsExternalHeuristics and ssr.format: 'cjs' are going to be removed in Vite 5.

That's Vite related.

> ReferenceError: exports is not defined in ES module scope

Minimal reproduction welcome.

> vike lastest examples react-full use commonjs、ssg vite build can find this bug

I don't understand that sentence.

And please don't create GitHub issues, but GitHub discussions if it isn't a Vike bug.
