### ISSUE TITLE
resolve.alias warning doesn't seem to account for libraries

### ISSUE THREAD

**Issue by zcolleyz** [vikejs/vike#1329]
### Description

With this config:

```js
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue2';

defineConfig({
  plugins: [
    vue()
  ],
  resolve: {
    alias: {
      '#example': '/example/path/
    }
  }
});
```

You get the following warning:

> defines an invalid resolve.alias which will be deprecated in the next major release: a path alias needs to start with a special character, see https://vike.dev/path-aliases#vite

Vike is getting sent this:

```js
[
  { find: '#example', replacement: '/example/path' },
  {
    find: /^\/?@vite\/env/,
    replacement: 'path/to/vite/dist/client/env.mjs'
  },
  {
    find: /^\/?@vite\/client/,
    replacement: 'path/to/vite/dist/client/client.mjs'
  },
  { find: 'vue', replacement: 'vue/dist/vue.runtime.esm.js' }
]
```
Should we really expect the '@vitejs/plugin-vue2' package to support Vike in this way?

**Comment by brillout** [comment]
Pre-released as `vike@0.4.149-commit-d815556`. Let me know if you still get the waning.

Related: https://github.com/vikejs/vike/issues/1146.

**Comment by zcolleyz** [comment]
Thank you Rom, doesn't seem to be showing that warning on that version

**Comment by zcolleyz** [comment]
@brillout timeline for us is end of January. If we don't reach out to you by then feel free to remind us.
