### ISSUE TITLE
Remove `?extractAssets` workaround in favor of `build.ssrEmitAssets`

### ISSUE THREAD

**Issue by brillout** [vikejs/vike#1339]
### Description

The [code for the `?extractAssets` workaround](https://github.com/vikejs/vike/blob/main/vike/node/plugin/plugins/extractAssetsPlugin.ts) is non-trivial and brittle. (See https://vike.dev/includeAssetsImportedByServer for why the workaround is needed.)

It would be more robust to use [`build.ssrEmitAssets`](https://vitejs.dev/config/build-options.html#build-ssremitassets) instead. (There is actually [an issues with a Babel plugin](https://gist.github.com/brillout/e03c8485da06bbcd338c623a23f9d347).)

See also:
 - https://github.com/vitejs/vite/pull/11430
 - https://github.com/vitejs/vite/discussions/13808

**Comment by nitedani** [comment]
I've tried but I'm stuck:
https://github.com/vikejs/vike/blob/nitedani/extract-assets/vike/node/plugin/plugins/ssrEmitAssets.ts

I don't know why, but the ssr manifest doesn't contain any of the css imports.
I tested tried it with the [path-aliases-v1](https://github.com/vikejs/vike/tree/nitedani/extract-assets/examples/path-aliases-v1) eample.

It works just fine here: https://stackblitz.com/edit/vitejs-vite-svc9fw?file=dist%2Fssr-manifest.json&terminal=dev
Here, the css is included in the ssr manifest.

**Comment by brillout** [comment]
Implemented by https://github.com/vikejs/vike/pull/1364.
