### ISSUE TITLE
Allow @ in resolved redirect URLs

### ISSUE THREAD

**Issue by sqs** [vikejs/vike#1347]
### Description

My intent is for Vike to redirect `/npm/*` to `https://cdn.jsdelivr.net/npm/*`, but this breaks when the `*` parameter matches something containing `@`. This is common in this use case because the `*` is matching npm package names (eg `@my-team/my-package`).

I see that `resolveRouteStringRedirect` forbids resolved URLs in redirection that contain `@`. Is that restriction necessary?

My vite.config.ts is:

```typescript
export default defineConfig({
    plugins: [
        // ...
        vike({
            redirects: {
                '/npm/*': 'https://cdn.jsdelivr.net/npm/*',
            },
        }),
  // ...
```

I get the following error:

```
Error: [vike][Wrong Usage] URL should not contain "@" unless it is a mailto link.
    at resolveRouteStringRedirect (file:///Users/sqs/src/github.com/sourcegraph/opencodegraph/node_modules/.pnpm/vike@0.4.150_vite@5.0.4/node_modules/vike/dist/esm/shared/route/resolveRedirects.js:38:9)
```

It works if I `throw redirect(...)` in an `+onBeforeRender.ts` file, but I would prefer to specify it in config (because, and this might be a misperception, that then it will actually redirect at the HTTP layer even in static page hosts).

p.s. Thank you for Vike! It is awesome.

**Comment by brillout** [comment]
Fix pre-released as `0.4.150-commit-d9acc70`.

> Thank you for Vike! It is awesome.

I'm glad you're enjoying it. Would your company be up for [sponsoring](https://github.com/sponsors/vikejs)?

**Comment by sqs** [comment]
Thank you so much!

Re: sponsoring, yes, absolutely, assuming we end up using the site that I've built with Vike. I have put a calendar reminder on myself for next week to confirm, at which point I will sponsor if we are indeed using it by then. If not, I'll probably sponsor it personally.

**Comment by brillout** [comment]
Thank you Quinn. We're beyond thrilled by the prospect of being sponsored by Sourcegraph. Fingers crossed 🤞

> the site that I've built with Vike

Let us know if you stumble upon any other blockers.
