### ISSUE TITLE
Misplaced config in prerendering context

### ISSUE THREAD

**Issue by rivatove** [vikejs/vike#1368]
### Description

When in prerendering context, the custom config defined through `meta` is not accessible under the config property of pageContext but in the pageContext object itself.

Expected:

```ts
{
  ...
  "config": {
    documentProps: {}
  },
  ...
}
```

Actual:

```ts
{
  ...
  "config": {
    ...
  },
  documentProps: {},
  ...
}
```

**Comment by brillout** [comment]
I don't think it's a bug. It's most likely a user land issue. But minimal reproduction if you disagree. (Making `meta` easier to use is work-in-progress.)
