### ISSUE TITLE
Parent's CSS stylesheets/assets from vike pack are not applied correctly without a dev mode if onRenderClient is empty.

### ISSUE THREAD

**Issue by UROjQ6r80p** [vikejs/vike#1378]
### Description

Hi,

If zero js is desired `onRenderClient` must be empty otherwise chunk with unused React client code is fetched.

So if I want zero js I need to reduce this:
```
// custom vike pack +onRenderClient.jsx
export { onRenderClient }

import { hydrateRoot } from 'react-dom/client'
import { PageShell } from './PageShell' // PageShell imports css internally

async function onRenderClient(pageContext) {
  const { Page, pageProps } = pageContext;
  console.log('PAGE CONTEXT', pageContext)
  if (!Page) throw new Error('Client-side onRenderClient() hook expects pageContext.Page to be defined')
  const root = document.getElementById('react-root')
  if (!root) throw new Error('DOM element #react-root not found')
  hydrateRoot(
    root,
    <PageShell pageContext={pageContext}>
      <Page {...pageProps} />
    </PageShell>
  )
}
```

To this (along other config options).
```
export { onRenderClient }

async function onRenderClient() {}

```

But then after build step assets and css stylesheets of parent elements **from vike pack** are not applied correctly.
It works in dev mode though.

Dev mode:
![image](https://github.com/vikejs/vike/assets/90694123/6417d438-bdd5-4403-bdcf-f5422eecbb69)

After build:
![image](https://github.com/vikejs/vike/assets/90694123/2edf4e1d-97e4-4b9b-af83-f79c3be371e7)

I think even with empty `onRenderClient` the assets should be applied correctly.
Assets works correctly if all the code is in the project folder directly, **but not in vike pack**.

Here is minimum reproducible repo:
https://github.com/UROjQ6r80p/vike-zero-js-assets-bug/tree/main

**Comment by brillout** [comment]
Can you create a minimal reproduction starting off from one of the examples or boilerplates?

**Comment by UROjQ6r80p** [comment]
> Can you create a minimal reproduction starting off from one of the examples or boilerplates?

Just making sure, I've provided minimal repo at the bottom:
https://github.com/UROjQ6r80p/vike-zero-js-assets-bug/tree/main

It is fresh made of vike express examples.
it's unrelated to the previous issue I made and this has only basic minimal structure (had to do monorepo, but really minimal because this bugs persist in vite pack)

**Comment by nitedani** [comment]
@brillout  Maybe `extractAssets` is not applied to imports in `+config.h`?

**Comment by nitedani** [comment]
Here is the issue:
https://github.com/vikejs/vike/blob/7b37ab506cd6d7cd61224fc297952df4ec05c0a4/vike/node/plugin/plugins/extractAssetsPlugin.ts#L157

**Comment by brillout** [comment]
> had to do monorepo, but really minimal because this bug persist only by extending vike pack config. if files from vike-pack were copied directly to the app renderer folder it works properly

Thank you, that's what I wanted to know.

> Here is the issue

Indeed, `extractAssets` skips `node_modules/`.

> Can this be fixed reasonably? Or instead go straight for ssrEmitAssets?

I'd say let's go straight for ssrEmitAsset. (Let me push the changes we discussed on Discord to your PR ASAP :).)

**Comment by brillout** [comment]
Note that after we merge the ssrEmitAssets PR, you’ll need to add node_modules/ code to ssr.noExternal.

It’s usually better to properly distribute the CSS of your framework instead.

**Comment by UROjQ6r80p** [comment]
Right, use cases where css or assets from vite packs need to be shipped are rather rare.

**Comment by brillout** [comment]
What I meant is that isomorphic code living in `node_modules/` shouldn't contain CSS imports (it isn't standard compliant and Node.js will crash). That's why I'm labelling this as `enhancement`.

Anyways, the situation will be "perfect" once we merge the PR. I think we can go ahead and close this. But let's reopen if things turn out to not behave as we want.
