### ISSUE TITLE
Sourcemap is likely to be incorrect: a plugin (vike:env) was used to transform files, but didn't generate a sourcemap for the transformation.

### ISSUE THREAD

**Issue by Csszabi98** [vikejs/vike#1402]
### Description

When creating production builds with source maps (external) the following warning shows up on the console:

```
(vike:env plugin) Sourcemap is likely to be incorrect: a plugin (vike:env) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

Versions:

```
"vite": "4.3.9",
"vike": "0.4.153",
```

**Comment by brillout** [comment]
I've a couple of ideas for how to get rid of that (false) warning, can you publish a reproduction? It doesn't have to be minimal.

**Comment by brillout** [comment]
I'll re-open if I can get me hands on a reproduction.
