### ISSUE TITLE
resolveRoute usage has warning in the console in prod mode

### ISSUE THREAD

**Issue by beneschjozsef** [vikejs/vike#1423]
### Description

I did it the v1 design migration. I have this warning in the console, because of this import in the +route.jsx: 'import { resolveRoute } from 'vike/routing''

in this file I found TODO comment: node_modules/vike/dist/esm/shared/route/routing.js
// TODO/v1-release - move:
//   import { resolveRoute } from 'vike/routing'
// to:
//   import { resolveRoute } from 'vike'

I tried the  import { resolveRoute } from 'vike' import too, which not working yet.

```
assert.js?v=5d3e7c2c:23 Error: [vike][Warning] You shouldn't `import { something } from 'vike/client/router'` when using Server Routing. The 'vike/client/router' utilities work only with Client Routing. In particular, don't `import { navigate }` nor `import { prefetch }` as they unnecessarily bloat your client-side bundle sizes.
    at assertWarning (assert.js?v=5d3e7c2c:94:21)
    at assertNoContradiction (assertRoutingType.js?v=5d3e7c2c:23:5)
    at assertServerRouting (assertRoutingType.js?v=5d3e7c2c:17:5)
    at entry.js:2:1
```

**Comment by brillout** [comment]
Indeed I could reproduce, let me have a look.

**Comment by brillout** [comment]
Fix pre-released in `0.4.156-commit-b89a01a`.

Btw. would your company be up for [sponsoring](https://github.com/vikejs/vike/issues/1350)?

**Comment by beneschjozsef** [comment]
Thanks! I will tell my manager.

**Comment by brillout** [comment]
Thanks, we'd massively appreciate it. Let us know how it goes 👀
