### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by brillout** [vikejs/vike#1435]
### Description

We're very much aware that the documentation is lacking in certain areas. Most notably:
 - Improving the landing page and make it higher-level.
 - ~~Clarifying the getting started path.~~ (mostly done)
 - ~~Improving the "easy path". (E.g. making advanced topics less "in your face" for users that use `vike-{react,vue,solid}` and, in general, for users that want to get started quickly and that are less interested in discovering Vike's full power.)~~ (mostly/partially done)
 - Graph showing when hooks are called.
 - Improve docs aesthetics.

That said, improving the documentation for advanced topics isn't the highest priority at the moment, such as custom render mode implementations and "build your own framework". We very much want to improve in that regard as well, but the aforementioned points are much higher priority.

In general, we'll be focusing a lot more on the documentation after we release the [`v1.0.0`](https://github.com/vikejs/vike/issues/985).

**Comment by uPixelar** [comment]
Hi there,

I suggest adding `npm install vike` as the first step on the documentation page [Add to existing app](https://vike.dev/add).
This will help clarify the initial setup process for users.

Thanks!

**Comment by brillout** [comment]
> * Clarifying the getting started path

I've just made changes, it's now mostly resolved. Although there is still a lot of potential to polish things.

> * Improving the "easy path". (E.g. making advanced topics less "in your face" for users that use `vike-{react,vue,solid}` and, in general, for users that want to get started quickly and that are less interested in discovering Vike's full power.)

This has improved a lot in last couple of weeks.
