### ISSUE TITLE
res.writeEarlyHints lock server response for 5 seconds

### ISSUE THREAD

**Issue by kcoet** [vikejs/vike#1452]
### Description

I'm having a problem where the server takes 5 seconds to fully respond to the HTML, I thought this was due to an Apollo instance problem but it turns out the code below is the cause.
```js
 if (res.writeEarlyHints) {
        res.writeEarlyHints({ link: earlyHints.map((e) => e.earlyHintLink) });
}
```
After removing this code the server responded in 301ms. This happened when I tested it in the production environment, locally I didn't feel anything.

when I use curl this HTML part to the top is responded quickly:

```html
  <!-- ... -->
  </footer>
    <script>
      window.__APOLLO_STATE__={};
    </script>
    <script id="vike_pageContext" type="application/json">{"pageProps":"!undefined","routeParams":{},"abortReason":"!undefined","_urlRewrite":null,"_urlRedirect":"!undefined","abortStatusCode":"!undefined","_abortCall":"!undefined","_pageContextInitIsPassedToClient":"!undefined","_pageId":"/pages","data":"!undefined"}</script>
```

And stuck for a few seconds before the server could respond to this part:

```html
  <script src="/assets/entries/entry-client-routing.7ZymZArp.js" type="module" async></script>
  <link rel="modulepreload" href="/assets/entries/pages.RnLKOcm3.js" as="script" type="text/javascript">
  <link rel="modulepreload" href="/assets/chunks/chunk-_jLpkPps.js" as="script" type="text/javascript">
  <link rel="modulepreload" href="/assets/chunks/chunk-hlDPvxQM.js" as="script" type="text/javascript">
  <!-- ... -->
</body>
```

**Comment by brillout** [comment]
Hm, that's surprising. If you apply this change:

```diff
- res.writeEarlyHints({ link: earlyHints.map((e) => e.earlyHintLink) });
+ console.log('link', { link: earlyHints.map((e) => e.earlyHintLink) });
```

1. What do you get and,  
2. do you still notice the delay?

Closing but I'll re-open if it turns out to be Vike related. (I'm inclined to think it's an issue with your server, but let's see.)

**Comment by kcoet** [comment]
this is the result:

```js
[
  "</assets/static/onRenderClient.as-qL5fR.css>; rel=preload; as=style",
  "</assets/entries/entry-client-routing.JeQtc64K.js>; rel=modulepreload; as=script",
  "</assets/entries/pages.N1BoR3C-.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-yehKyfPf.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-hlDPvxQM.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-tDvhWMUH.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-j34KyF5w.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-0CokXpuq.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-bvcKXwEt.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-ExQLDb0_.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-CJ30i95j.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk--W6W-tbi.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-ZyM0AsWE.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-No6Bd6Ck.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-ZBkmtNoT.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-xz6E86XN.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-Q2nSWfkk.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-QDr74C2f.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-7UmpWu7d.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-_dkiVqDr.js>; rel=modulepreload; as=script",
  "</assets/chunks/chunk-q6Jm8506.js>; rel=modulepreload; as=script",
];
```

**Comment by brillout** [comment]
I don't see anything out of the ordinary. If you still notice a delay then I'll need a minimal reproduction. I'll re-open then.

**Comment by kcoet** [comment]
I don't think it's a Vike problem, I suspect it's an HTTP/2 problem in Nginx. When I enable earlyHints Vike and HTTP/2, the site cannot be accessed at all returning the error ERR_HTTP2_PROTOCOL_ERROR in the browser.

The 5 second lockout issue occurred when I disabled HTTP/2 and enabled Vike's earlyHints.

Temporarily fixed by disabling Vike's earlyHints and enabling HTTP/2 to work, the site was able to respond quickly.

I'm still figuring out why Vike's earlyHints doesn't work with HTTP/2.

I found a good write up on medium that was having similar issues and using the old vike: https://medium.com/@imhamoro/have-you-ever-experienced-issues-with-early-hints-feat-http2-103-5667c6181ae5

**Comment by kcoet** [comment]
Sure, if I don't share the HTTP/2 Nginx + EarlyHints solution then I'm using this solution:

> Temporarily fixed by disabling Vike's earlyHints and enabling HTTP/2 to work, the site was able to respond quickly.

**Comment by brillout** [comment]
It would be nice to find the issue on Nginx's error tracker, so we can keep track of progress.

**Comment by AurelienLourot** [comment]
Not sure if related but we also heard in the past of an issue when using nginx together with HTML streaming: https://github.com/vikejs/vike/discussions/1316#discussioncomment-7793560

**Comment by kcoet** [comment]
> Not sure if related but we also heard in the past of an issue when using nginx together with HTML streaming: [#1316 (reply in thread)](https://github.com/vikejs/vike/discussions/1316#discussioncomment-7793560)

I'm not using streaming, using Apollo `renderToStringWithData`.

Also tried `httpResponse.pipe(res)`, didn't solve the problem.

Have also tried switching all earlyLinks from modulepreload to preload, based on this comment http://disq.us/p/2qfff9z, no luck.

Still returns ERR_HTTP2_PROTOCOL_ERROR

**Comment by simplecommerce** [comment]
> I don't think it's a Vike problem, I suspect it's an HTTP/2 problem in Nginx. When I enable earlyHints Vike and HTTP/2, the site cannot be accessed at all returning the error ERR_HTTP2_PROTOCOL_ERROR in the browser.
> 
> The 5 second lockout issue occurred when I disabled HTTP/2 and enabled Vike's earlyHints.
> 
> Temporarily fixed by disabling Vike's earlyHints and enabling HTTP/2 to work, the site was able to respond quickly.
> 
> I'm still figuring out why Vike's earlyHints doesn't work with HTTP/2.
> 
> I found a good write up on medium that was having similar issues and using the old vike: https://medium.com/@imhamoro/have-you-ever-experienced-issues-with-early-hints-feat-http2-103-5667c6181ae5

I have the same issue on my end.
I noticed that without changing any configuration and using Node v16, it works.
But if I switch to Node v18 or v20, it gives me the same error as you.
And it only seems to be related to what you are mentioning with `writeEarlyHints` because I tested it also by commenting it and the site loads but causes other issues.

I tested the same code on Windows to make sure it wasn't a code problem, and it runs fine on my local machine on Node v18.

I checked for different configurations on nginx but didn't find a solution yet either.

**Comment by brillout** [comment]
Thanks for reporting back on this, I've added a link to your comment at https://vike.dev/nginx.

**Comment by Uzume** [comment]
Apparently nginx has some support for [RFC 8297](https://datatracker.ietf.org/doc/html/rfc8297), see https://github.com/nginx/nginx/discussions/332

**Comment by brillout** [comment]
@Uzume 👍 Docs updated: https://github.com/vikejs/vike/commit/840fd29b3e97b01fa9c0fbdeb8a5021001b16445.
