### ISSUE TITLE
Config inheritance seems to be in reverse order from docs

### ISSUE THREAD

**Issue by tlancina** [vikejs/vike#1458]
### Description

Hello! https://vike.dev/config#overridable-defaults says "The +config.h.js file of pages (/pages/some-page/+config.h.js) can override default values defined by /pages/+config.h.js.", but it didn't seem to be working that way (playing around with defining Page meta to manually control render modes). Debugging the issue it seems like the sort order in the implementation is to have longer path lengths first, so when they are iterated over, shorter paths clobber config set by more specific ones.

https://github.com/vikejs/vike/blob/d90bba5f47bd069913a01cbfbb55170f356aab09/vike/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.ts#L809

<img width="317" alt="image" src="https://github.com/vikejs/vike/assets/804331/248df788-6860-46bb-93d4-5d36fe0334fb">

I'm on version 0.4.156. Can you confirm you are seeing this as well? A simple repro is to define `meta: { Page: { env: { server: true, client: false } }` in `pages/` or `render/` config and then override with `meta: { Page: { env: { server: true, client: true } }` in a specific path and check for the client side bundle on load. 

If I change the above line to the following then it works as expected:
```ts
Object.entries(interfaceFilesRelevant).reverse().forEach(([_locationId, interfaceFiles]) => {
```

Happy to PR this as well 😄

**Comment by brillout** [comment]
Let me try to reproduce.

> Happy to PR this as well 😄

Sure, we can always close it anyways if there is a better solution :)

**Comment by brillout** [comment]
Indeed, I could reproduce and your fix was correct.

[Fix](https://github.com/vikejs/vike/commit/a1101c17fd966feffc20c92e3d985f216553487d) pre-released as `0.4.160-commit-a1101c1`.

Also, in case your company is up for it: [Support Vike #1350](https://github.com/vikejs/vike/issues/1350).

**Comment by tlancina** [comment]
Hey thanks for the quick response. I wasn't sure what sort of sort guarantees `interfaceFilesRelevant` had potentially from other places so was hesitant to suggest it as a permanent fix.

I don't have an employer at the moment, but I respect the hustle! Just sent you some beer money. Thanks for Vike!

**Comment by brillout** [comment]
Thank you 🍻
