### ISSUE TITLE
Support configurable sources of framework files

### ISSUE THREAD

**Issue by uifox** [vikejs/vike#1464]
### Description

In a Vike app Vike currently looks for pages in the `/pages` folder. The name of framework files with special meaning and parsed by Vike start with the plus sign (e.g. `+config.h.ts`, `+route.ts`, etc.). This convention is comfortable and acceptable, however should be configurable.

It should be possible to instruct Vike where to look for these files. It would be desirable to have Vike look into some package dependencies in node_modules upon request.

**A use case:**
A main Vike app has dependencies on `module_a` and `module_b`, each of which contains pages and "+" files, e.g.:

```
pages/
  main/
    +Page.vue
    +route.ts
node_modules/
  module_a/
    pages/
      hello/
        +Page.vue
        +route.ts
  module_b/
    pages/
      goodbye/
        +Page.vue
        +route.ts
```

It should be possible to configure Vike such that the "main", "hello" and "goodbye" pages are all recognized.

**Comment by brillout** [comment]
Crawling `node_modules/some-package/` isn't supported by design, you should use `extends` instead. See how `vike-react` works.

**Comment by brillout** [comment]
Being able to load pages over config files isn't supported yet but it's very much a priority (atlhough not the highest). What is it your building?

**Comment by uifox** [comment]
We have one main Vike app that has dependencies that should contribute pages to the main app. If we can't get Vike to recognize the +Page.ts, +config.h.ts, +route.ts, etc. files in the dependencies then we cannot - or only in a fairy limited way - use Vike in the dependencies. We'd want full access to Vike in all the dependencies too.

Isn't [ExtensionUserProvided](https://github.com/vikejs/vike/blob/fda57a2fb27e50886488e64a9573a15f5e703b92/vike/shared/ConfigVike.ts#L5-L14) what I would need?

**Comment by uifox** [comment]
If it is deprecated and will be removed, what is the suggested path to take?

**Comment by brillout** [comment]
You'll have to wait until the feature I mentioned is implemented. This use case is quite advanced and niche so, while it's a priority, it isn't the highest priority right now.
