### ISSUE TITLE
bug in vite-plugin-ssr's source code

### ISSUE THREAD

**Issue by niteshghule2** [vikejs/vike#1470]
### Description

I am using Vue js 3. The browser console log shows the following error -
entry.js:24 Uncaught (in promise) Error: [vite-plugin-ssr@0.4.112][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at getPageContextSerializedInHtml.js?v=59694482:38:9
    at Array.map (<anonymous>)
    at getPageContextsSerializedInHtml (getPageContextSerializedInHtml.js?v=59694482:36:41)
    at getPageContexts (getPageContext.js?v=59694482:20:26)
    at hydrate (entry.js:15:40)
    at entry.js:9:1

**Comment by brillout** [comment]
Update to the latest version. I'll re-open if you still get this.
