### ISSUE TITLE
httpResponse.getReadableNodeStream() Not in Types

### ISSUE THREAD

**Issue by dajinchu** [vikejs/vike#1473]
### Description

`httpResponse.getReadableNodeStream()` is available at runtime but not documented in typescript. Is that intentional?

**Comment by brillout** [comment]
It used to be deprecated but we decided to undeprecate it in the latest release.

Fix pre-released in `0.4.160-commit-f473528`.

**Comment by brillout** [comment]
(In general, you should use `pipe()` whenever possible, see updated docs at https://vike.dev/streaming.)
