### ISSUE TITLE
Typing bug on PageContextConfig

### ISSUE THREAD

**Issue by tumidi** [vikejs/vike#1532]
### Description

I'm adding properties to the `Config` type as explained [here](https://vike.dev/meta#typescript).

```typescript
declare global {
  namespace Vike {
    interface Config {
      /** Hook called before the page is rendered (server) */
      onInit?(
        this: void,
        pageContext: Pick<PageContext, 'routeInfo' | 'store'>,
      ): void | Promise<void>
    }
}

export {}
```

In `onBeforeRender`, I'm trying to access `pageContext.config.onInit`:

```typescript
import type { OnBeforeRenderAsync } from 'vike/types'

const onBeforeRender: OnBeforeRenderAsync = async function (pageContext) {
  // (...)
  const { onInit } = pageContext.config // 💥 TS: Property 'onInit' does not exist on type 'PageContextConfig'
  // (...)
}
```

I would expect the `Vike.Config` to be merged into [`PageContextConfig`](https://github.com/vikejs/vike/blob/a2e5cd0dcf306db4ffd254c4539a5aaa4f04e0ff/vike/shared/page-configs/Config/PageContextConfig.ts#L8).

### Workaround

Suppressing the error using a type assertion or augment `PageContextConfig`.

### Fix

Add `Vike.Config` to `PageContextConfig`.

**Comment by brillout** [comment]
Fix pre-released as `0.4.165-commit-74b18b0`.

@tumidi Thanks for the PR!
