### ISSUE TITLE
Custom PageContext returns `undefined` for all custom values

### ISSUE THREAD

**Issue by alycda** [vikejs/vike#1537]
### Description

Hi, I have followed the guides at https://vike.dev/pageContext#custom but the values I pass are ALWAYS undefined, server-side and client-side. 

```
...
import cookieParser from 'cookie-parser'
...

  const app = express()

  app.use(compression())
  app.use(cookieParser())

...

    const pageContextInit = {
      urlOriginal: req.originalUrl,

      // pageContext.headers – e.g. make cookies available over pageContext.headers.cookies
      headers: req.headers,

      cookies: req.cookies,
    }
```

// +config.ts
```
export default {
  passToClient: [
    'headers',
    'cookies',
  ]
}

```

terminal console output for `headers` and `cookies` is undefined, as well as the console output in Browser DevTools. I have also tried adding a hardcoded string value and that also returns undefined.

**Comment by phonzammi** [comment]
Hi @alycda 
Can you provide a minimal repro, please?

**Comment by alycda** [comment]
Hi, I found the issue. This project is within an NX monorepo, so the command I used to run was `pnpm nx serve apps/env-switcher` which uses `@nx/vite:dev-server`. But running with `pnpm dev` seems to work (I assume thanks to ts-node).

**Comment by phonzammi** [comment]
By default, your server code isn't processed by Vite: [issue#562](https://github.com/vikejs/vike/issues/562)

**Comment by phonzammi** [comment]
I'm sorry. The point is when you run the dev server, what script does it execute, if it's `vite` or `vite dev` then it doesn't run your express server.

**Comment by alycda** [comment]
ah, I see. that file (index.ts) wasn't automagically executed by `@nx/vite:dev-server` so the values _were_ undefined (and I correctly got errors regarding `headers` and `cookies` not being passed to client without changes to +config.ts)
