### ISSUE TITLE
New CLI command `$ vike eject`

### ISSUE THREAD

**Issue by brillout** [vikejs/vike#1553]
### Description

Make Vike integrations ejectable.

For example `$ vike eject vike-react-apollo` would essentially do two things:
 - Move code from `node_modules/vike-react-apollo/` to the user-land `pages/`. (Or better yet its TypeScript source code.)
 - Remove `vike-react-apollo` from `package.json#dependencies`.

Eject is also nice from a marketing perspecitve as it doubles down on the [Optional Control](https://vike.dev/why#optional-control) USP.

WIP: https://github.com/vikejs/vike/pull/1798  
Prior art: https://github.com/brillout/eject

**Comment by tbjgolden** [comment]
This would be massive in terms of the company project we're considering this for

**Comment by brillout** [comment]
@tbjgolden How so?

**Comment by tbjgolden** [comment]
Optional control is something we care about - we'd obviously prefer to trust a preset that others also use but if needs must we'd be able to maintain some custom code

Nothing specific in mind, more of a insurance policy that makes it easier to get sign off on it

**Comment by brillout** [comment]
Yes, that‘s the idea. In the meantime you can manually eject.

**Comment by brillout** [comment]
@tbjgolden Also btw. in case that's something your company would be up for, Vike is looking for [sponsors](https://github.com/vikejs/vike/issues/1350). (As a bonus Vike could then, for example, prioritize eject.)

**Comment by phonzammi** [comment]
Another use case I can think of is when a user may want to eject specific files, like `onRenderHtml.ts` and `onRenderClient.ts`, rather than ejecting everything.

For example `$ vike eject vike-react onRenderHtml,onRenderClient` would essentially do two things:

- Copy code from `node_modules/vike-react/` to the user-land `pages/` (or `renderer/`).
- Add import of those files to `+config.ts`. (May not be necessary ?)

**Comment by nitedani** [comment]
I'm not sure that would work, unless every imported module(in the ejected files) are (re)exported from `vike-react`.

**Comment by phonzammi** [comment]
> I'm not sure that would work, unless every imported module(in the ejected files) are (re)exported from `vike-react`.

Yeah, I think you're right. I've updated my comment.

**Comment by snake-py** [comment]
I just wanted to pop in here and let you guys now that development moved into its own repository. We just released a first version. 

See [docs](https://vike.dev/eject) and [repository](https://github.com/snake-py/eject).

**Comment by brillout** [comment]
I guess we can mark this as completed. Props to @snake-py :100:
