### ISSUE TITLE
In popstate listener, triggeredBy is misspelled triggedBy

### ISSUE THREAD

**Issue by bravomartin** [vikejs/vike#1563]
### Description

There is a typo in [the code](https://github.com/search?q=org%3Avikejs%20triggedBy&type=code) that doesn't match the [documentation](https://vike.dev/navigate#history-pushstate).

In the popstate event listener, vike adds a custom variable to identify who triggered the event. in the code it's spelled `triggedBy`, when it should be `triggeredBy`, as it is correctly spelled in the docs.

**Comment by brillout** [comment]
Thanks.

To my knowledge only very few users use this, thus I ain't bumping the major semver even though it's a breaking change.

Released in `0.4.166`.

CC @dajinchu

**Comment by bravomartin** [comment]
Thanks for such quick reaction! Best

**Comment by brillout** [comment]
:+1: Btw. in case your company would be up for it: we're looking for [sponsors](https://github.com/vikejs/vike/issues/1350). Sponsoring is making a massive difference.
