### ISSUE TITLE
App crashed - tried to load a non existent page (other non existent pages just show 404)

### ISSUE THREAD

**Issue by llintel** [vikejs/vike#1586]
### Description

Error: [vite-plugin-ssr@0.4.142][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
    at file:///C:/Users/my_user/Documents/GitHub/my_project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage/log404/index.js:81:9  
    at Array.forEach (<anonymous>)
    at getPagesAndRoutesInfo (file:///C:/Users/my_user/Documents/GitHub/my_project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage/log404/index.js:73:18)
    at log404 (file:///C:/Users/my_user/Documents/GitHub/my_project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage/log404/index.js:18:13)
    at renderPageAlreadyPrepared (file:///C:/Users/my_user/Documents/GitHub/my_project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:128:15)
    at renderPageAndPrepare (file:///C:/Users/my_user/Documents/GitHub/my_project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:93:12)
    at file:///C:/Users/my_user/Documents/GitHub/my_project/node_modules/vite-plugin-ssr/dist/esm/node/plugin/shared/getHttpRequestAsyncStore.js:68:35
    at renderPage (file:///C:/Users/my_user/Documents/GitHub/my_project/node_modules/vite-plugin-ssr/dist/esm/node/runtime/renderPage.js:46:50)
    at file:///C:/Users/my_user/Documents/GitHub/my_project/server/index.js:58:25
    
I restarted the server and it worked just fine, not sure what happened here.
here's my package.json
 ```json
 {
  "scripts": {
    "dev": "npm run server:dev",
    "prod": "npm run build && npm run server:prod",
    "build": "vite build",
    "server:dev": "nodemon --watch server ./server/index.js",
    "server:prod": "cross-env NODE_ENV=production node ./server",
    "start": "node ./server/index.js"
  },
  "dependencies": {
    "@heroicons/vue": "^2.1.3",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue/compiler-sfc": "^3.3.4",
    "@vue/server-renderer": "^3.3.4",
    "compression": "^1.7.4",
    "cross-env": "^7.0.3",
    "express": "^4.18.2",
    "sirv": "^2.0.3",
    "vite": "^4.4.9",
    "vite-plugin-ssr": "^0.4.142",
    "vue": "^3.3.4"
  },
  "type": "module"
}
```

heres the block of code that the error originates from:
```js
// Vite-plugin-ssr middleware. It should always be our last middleware (because it's a
// catch-all middleware superseding any middleware placed after it).
app.get('*', async (req, res, next) => {
    const pageContextInit = {
        urlOriginal: req.originalUrl
    }
    const pageContext = await renderPage(pageContextInit)
    const { httpResponse } = pageContext
    if (!httpResponse) {
        return next()
    } else {
        const { body, statusCode, headers, earlyHints } = httpResponse
        if (res.writeEarlyHints && earlyHints.length > 0 && req.httpVersionMajor >= 2) {
            // GAE does not support HTTPv2 which is required for early hints.
            // need to check if http is 2 or it will stall out and give 503 error on deployed server.
            res.writeEarlyHints({ link: earlyHints.map((e) => e.earlyHintLink) })
        }
        headers.forEach(([name, value]) => res.setHeader(name, value))
        res.status(statusCode)

        res.send(body)
    }
})
```

I am running this on Windows 10 pro. Server is Ubuntu but i haven't had this issue on the server or ever before.
The error seems to be resolved for me but i have no idea what happened and would like to provide information to fix whatever it is.

**Comment by brillout** [comment]
Update to the latest Vike version. I'll re-open if you still have the issue.
