### ISSUE TITLE
How to set scrollPosition to auto

### ISSUE THREAD

**Issue by wanglanglang0318** [vikejs/vike#1604]

**Comment by wanglanglang0318** [comment]
When I use the browser to move forward and backward, I want the scroll bar to maintain the current scrolling position.

**Comment by brillout** [comment]
- https://vike.dev/clientRouting#settings  
- https://brillout.github.io/rules#try
- Don't mis-use GitHub issues for asking questions.

**Comment by wanglanglang0318** [comment]
Iti is not work

**Comment by brillout** [comment]
Minimal reproduction welcome.

**Comment by wanglanglang0318** [comment]
scrollPosition is set to automatic, but I looked at all APIs and there is no corresponding option or setting.

**Comment by phonzammi** [comment]
@wanglanglang0318, have you try like this?

`<a href="/some/url" keep-scroll-position>Link</a>`
