### ISSUE TITLE
history.state.triggedby  and history.state.triggeredby

### ISSUE THREAD

**Issue by wanglanglang0318** [vikejs/vike#1610]
### Description

history.state 触发着有俩个不同的单词
history.state triggers two different words

**Comment by brillout** [comment]
Please use English.

**Comment by brillout** [comment]
> triggedby

This has been fixed recently.

**Comment by brillout** [comment]
I know, this has been fixed.

**Comment by wanglanglang0318** [comment]
Which version has the code been released?

**Comment by brillout** [comment]
https://brillout.github.io/rules#try

**Comment by wanglanglang0318** [comment]
thanks
