### ISSUE TITLE
`urlParsed` removes trailing slash

### ISSUE THREAD

**Issue by openscript** [vikejs/vike#1629]
### Description

When the `urlOriginal` is `/en/index.pageContext.json?asd=asd` and in the address bar is displayed `/en/?asd=asd` the `urlPathname` is `/en`.  When the `urlOriginal` is `/en/?asd=asd` the `urlPathname` is `/en/`.

This behavior is not influenced by `disableUrlNormalization: true`.

In my opinion the `urlPathname` should be `/en/` when the `urlOriginal` is `/en/index.pageContext.json?asd=asd`.

**Comment by openscript** [comment]
I would be happy to create a PR for this. Probably this lines need to be changed:

https://github.com/vikejs/vike/blob/6dedbfbda96357dcb1fbc21b6643d099948993b4/vike/node/runtime/renderPage/handlePageContextRequestUrl.ts#L25-L36

Are there unit tests for this? Where would you add a unit test?

**Comment by brillout** [comment]
I agree and PR welcome :+1:

I also agree that'd be good to add some Vitest test for it and create a file `vike/vike/node/runtime/renderPage/removePageContextUrlSuffix.spec.ts`. Let's export `removePageContextUrlSuffix()` and after the PR is merged I'll move `removePageContextUrlSuffix()` in its own file. (Let's move it to its own file later so it's easier for me to read the diffs you made to `removePageContextUrlSuffix`.)

**Comment by openscript** [comment]
Inside `removePageContextUrlSuffix()` we cannot know if it was originally `/en/?asd=asd` or `/en?asd=asd`. Should we read Vikes option `trailingSlash` and act according to that?

**Comment by brillout** [comment]
Yes, that's an issue: there is no way to know whether `/en/index.pageContext.json` is for a `/en/` or `/en` URL. I'm thinking a trick could be to use `/en//index.pageContext.json` if the URL is `/en/`?

> Inside `removePageContextUrlSuffix()` we cannot know if it was originally `/en/?asd=asd` or `/en?asd=asd`. Should we read Vikes option `trailingSlash` and act according to that? If so, should `trailingSlash` be a param in `removePageContextUrlSuffix()` or for `parseUrl()`?

That would be a brittle solution as it would fail for `/en` URLs then.

**Comment by brillout** [comment]
Ah, actually more natural: `/en/index.pageContext.json/`. Much clearer I think.

**Comment by openscript** [comment]
Where would the trailing slash `/en/index.pageContext.json/` being added?

**Comment by brillout** [comment]
See `vike/shared/getPageContextRequestUrl.ts`

**Comment by brillout** [comment]
Closing as it doesn't seem fixable, see https://github.com/vikejs/vike/pull/1632#issuecomment-2104462175.

@openscript Let me know whether this is a blocker for you. Otherwise I'll move on and focus on other priorities.

**Comment by openscript** [comment]
Thank you @brillout. Even though a nice way to handle this, I'm happy that we collaborated.

It's not a blocker as I can handle it case by case in my implementation.
