### ISSUE TITLE
Offer `href` in `urlParsed`

### ISSUE THREAD

**Issue by openscript** [vikejs/vike#1630]
### Description

In my opinion `urlParsed` should contain a [`href`](https://developer.mozilla.org/en-US/docs/Web/API/URL/href). My reasoning is [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) also contains that and the DX would improve. 

For example https://vike.dev/i18n describes:

```ts
const urlWithoutLocale = `${origin || ''}${pathnameWithoutLocale}${searchOriginal || ''}${hashOriginal || ''}`
```

This would become
```ts
const urlWithoutLocale = url.href.replace(url.pathname, url.pathnameWithoutLocale)
```

**Comment by brillout** [comment]
Agreed :+1: Would you be up for PR for this as well? AFAICT this one should actually be fairly easy (easier than the other one).

(On a tangent, I was thinking it would also be nice to offer/document an easier way to manipulate the URL. The issue with `url.href.replace(url.pathname, url.pathnameWithoutLocale)` is that it may fail for example for a `url.pathname` that is `/en` and a URL `/en?movies/endeavour` which would become `/?movies/deavour`.)

**Comment by openscript** [comment]
> Would you be up for PR for this as well?

Sure, I'll give it a try. :)

**Comment by brillout** [comment]
Done & released, see `modifyUrl()` at https://vike.dev/i18n.

Btw. would your company be up for sponsoring (#1350)? It makes a foundamental difference!

**Comment by openscript** [comment]
> Btw. would your company be up for sponsoring (https://github.com/vikejs/vike/issues/1350)? It makes a foundamental difference!

Absolutely. When we earn the first time money with a project where Vike is involved, we will do that.

**Comment by brillout** [comment]
> Absolutely. When we earn the first time money with a project where Vike is involved, we will do that.

Thank you, that's much appreciated :green_heart:
