### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by joshua-v-dev** [vikejs/vike#1644]
### Description

web:build: error during build:
web:build: Error: [vike@0.4.171][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
web:build:     at Object.transform (file:///C:/Users/joshu/JV%20Labs/JVStudio/external/web/Streetbeefs%20Scrapyard/node_modules/.pnpm/vike@0.4.171_react-streaming@0.3.28_vite@5.2.11/node_modules/vike/dist/esm/node/plugin/plugins/fileEnv.js:101:13)
web:build:     at file:///C:/Users/joshu/JV%20Labs/JVStudio/external/web/Streetbeefs%20Scrapyard/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:19778:40
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build: ERROR: command finished with error: command (C:\Users\joshu\JV Labs\JVStudio\external\web\Streetbeefs Scrapyard\apps\web) C:\Program Files\nodejs\pnpm.cmd run build exited (1)
web#build: command (C:\Users\joshu\JV Labs\JVStudio\external\web\Streetbeefs Scrapyard\apps\web) C:\Program Files\nodejs\pnpm.cmd run build exited (1)

**Comment by brillout** [comment]
Add the following before line `101` of `/C:/Users/joshu/JV%20Labs/JVStudio/external/web/Streetbeefs%20Scrapyard/node_modules/.pnpm/vike@0.4.171_react-streaming@0.3.28_vite@5.2.11/node_modules/vike/dist/esm/node/plugin/plugins/fileEnv.js` and report back the result.

```diff
            const envWrong = isServerSide ? 'client' : 'server';
+         console.log('options', options);
+         console.log('id', id);
            assert(!id.includes(`.${envWrong}.`));
```

**Comment by joshua-v-dev** [comment]
I found resolution.

**Comment by brillout** [comment]
What was the issue? Vike should print a better error message.
