### ISSUE TITLE
New setting `crawlWithGit`

### ISSUE THREAD

**Issue by brillout** [vikejs/vike#1655]
### Description

Toggle whether Vike uses Git (and `.gitignore`) or `fast-glob` to crawl + files.

**Comment by ChristophP** [comment]
Since we have a mixture of generated and checked-into-git pages, that would indeed be great to have since otherwise it would force us to work around it by copying aro  und files as described here from [this issue](https://github.com/vikejs/vike/discussions/1541#discussioncomment-9549035).

> Workaround: We could force all of the plus files to be generated but it wouldn't make a lot of sense from our perspective since some files are "user files" and others are "framework files". We could do some trickery like keeping the framework files in a different place and copy them into the Vike root at build time but that would be pretty messy.

Having this would allow us to upgrade to the V1 design smoothly.

**Comment by ChristophP** [comment]
One thing to add, which is not relevant now, but might be something to speed up the crawling in the future.
[Node 22 will feature built-in globbing.](https://nodejs.org/en/blog/announcements/v22-release-announce#glob-and-globsync)
Once it becomes available it might be worth a try to see if that offers a well-enough performance improvement over libs like `fast-glob`

**Comment by brillout** [comment]
Implemented and pre-released as `0.4.172-commit-c1b0884`.

```js
// vite.config.js

import vike from 'vike/plugin'

export default {
  plugins: [
    vike({
      crawl: { git: false }
    })
  ]
}
```

It's marked as experimental and it isn't documented (yet), because it's going to be moved from `vite.config.js` to the upcoming `vike.config.js`. The setting itself will stay and can be considered stable.

**Comment by ChristophP** [comment]
Awesome, thank you will try later.

**Comment by brillout** [comment]
:+1: Let me know if you run into any issues.

**Comment by ChristophP** [comment]
Works nicely :+1:

**Comment by brillout** [comment]
Deprecated in favor of `VIKE_CRAWL={git:false}`, see https://vike.dev/filesystem-routing.
