### ISSUE TITLE
Updated to 0.4.172 and got internal Vike bug

### ISSUE THREAD

**Issue by jscottsf** [vikejs/vike#1659]
### Description

0.4.171 works perfectly. This happens on update to 0.4.172.

Using v1 design API with Vue.

Pasted from browser console below. No server-side errors logged.

```
createErrorWithCleanStackTrace.js?v=9594635f:4 Uncaught Error: [vike@0.4.171][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at createErrorWithCleanStackTrace (createErrorWithCleanStackTrace.js?v=9594635f:4:17)
    at assert (assert.js?v=9594635f:53:27)
    at parseGlobResults (parseGlobResults.js?v=9594635f:9:5)
    at setPageFiles (setPageFiles.js?v=9594635f:10:58)
    at pageFiles.js?v=9594635f:4:1
```

Can provide more info as needed. Thx!

**Comment by brillout** [comment]
Thank you for opening the issue.

Click on `parseGlobResults.js?v=9594635f:9:5` and let me know which `assert()` you see: it's the one that is failing.

**Comment by jscottsf** [comment]
It landed on the first assert.

```
function parseGlobResults(pageFilesExports) {
    assert(hasProp(pageFilesExports, 'isGeneratedFile'));

```

**Comment by brillout** [comment]
That's quite unexpected: `isGeneratedFile` doesn't exist anymore. Did you `$ rm -rf node_modules/.vite/`?

**Comment by jscottsf** [comment]
Um, no. Lol. That fixed it!!! This was probably noted somewhere that I neglected to read.

Sorry about that.

And BTW, the work that has been done on this framework lately has been fantastic. The detailed docs are appreciated. Thank you!

**Comment by brillout** [comment]
No worries & I'm glad you're enjoying Vike.
