### ISSUE TITLE
[vike@0.4.172][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours)

### ISSUE THREAD

**Issue by gajus** [vikejs/vike#1660]
### Description

```
page error {
  name: 'Error',
  message: '[vike@0.4.172][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).',
  stack: 'Error: [vike@0.4.172][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).\n' +
    '    at se (http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:1:1742)\n' +
    '    at s (http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:2:842)\n' +
    '    at Qr (http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:2:29740)\n' +
    '    at Ut (http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:2:37959)\n' +
    '    at d (http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:3:14485)\n' +
    '    at g (http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:3:13160)\n' +
    '    at J (http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:3:13080)\n' +
    '    at ro (http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:3:18062)\n' +
    '    at no (http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:3:18010)\n' +
    '    at http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:3:18220'
}
```

Not clear how to gather more information about the error.

**Comment by brillout** [comment]
In your browser's console, click on `http://127.0.0.1:8080/static/chunk-entries/entry-client-routing.Cv8FsNF8.js:2:842` which should then show you an `assert()` call (the one that is failing). Which `assert()` is it? That's likely enough information for me to fix these kind of bugs.

**Comment by brillout** [comment]
If you don't see any `assert()` call, then try the stack trace entry one up/down.

**Comment by gajus** [comment]
```
Uncaught (in promise) Error: [vike@0.4.172][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at createErrorWithCleanStackTrace (entry-client-routing.DjMs_z8j.js:97:15)
    at assert (entry-client-routing.DjMs_z8j.js:171:25)
    at getPageFilesAll (entry-client-routing.DjMs_z8j.js:1951:3)
    at createPageContext (entry-client-routing.DjMs_z8j.js:2377:42)
    at getPageContextBegin (entry-client-routing.DjMs_z8j.js:3488:31)
    at renderPageNominal (entry-client-routing.DjMs_z8j.js:3377:31)
    at renderPageClientSide (entry-client-routing.DjMs_z8j.js:3370:9)
    at render (entry-client-routing.DjMs_z8j.js:3777:25)
    at installClientRouter (entry-client-routing.DjMs_z8j.js:3771:25)
    at entry-client-routing.DjMs_z8j.js:3794:1
```

```ts
const { pageFilesAll, pageConfigs, pageConfigGlobal } = globalObject$5;
assert(pageFilesAll && pageConfigs && pageConfigGlobal);
```

Looks like all of those properties are undefined.

For context, this happened after attempting update:

```diff
-"vike": "0.4.167",
+"vite": "^5.0.12",
-"vike": "0.4.172",
+"vite": "^5.2.12",
```

**Comment by brillout** [comment]
Hm, that's quite unexpected.

Have you removed all caches? For example `$ rm -rf node_modules/.vite/`. Make sure to remove all possible caches; a cache would explain the mismatch between what Vike's client expects and what Vike's server runtime actually returns.

**Comment by gajus** [comment]
It is not cache. Have this happening in isolated CI environment and also locally.

**Comment by brillout** [comment]
Maybe some kind of minification or transformer then.

Inside `dist/server/` (or `{vite.config.js#build.outDir}/server/`), do you have any occurrence of `pageFilesAll`, `pageConfigs`, or `pageConfigGlobal`?

> Looks like all of those properties are undefined.

It's even more unexpected that all *three* are `undefined`.

**Comment by gajus** [comment]
I think you are right about this being a minification issue (or related). I disabled all Vite plugins & minification and it is working now. Will try to narrow down to a specific setting and report back.

**Comment by brillout** [comment]
The bottom line is that the page entries generated at `dist/client/` should export `pageFilesAll`, `pageConfigs`, and `pageConfigGlobal`.

If you only upgrade Vike (without upgrading Vite), then I'd expect things to work then. If you only upgraded Vike + Vite then maybe it's some kind of Rollup regression.

Feel free to let me know if you have any question, and feel free to PM me on Discord.

**Comment by gajus** [comment]
Looks like it is not a plugin, but a Rollup setting of `vite.config.ts#build.rollupOptions.treeshake.preset=smallest` setting.

Disabling this setting makes it work again. This solves the issue for us.

**Comment by brillout** [comment]
Makes sense, thanks for circling back on this. Also thanks for sponsoring Vike :green_heart: it makes a *massive* difference. Kind regards, Rom
