### ISSUE TITLE
Error reported when relying on vike-pinia to start.   10:56:07 [vike][config][Wrong Usage] vike-pinia sets an unknown config onCreateAppPinia

### ISSUE THREAD

**Issue by DemocracyAndScience** [vikejs/vike#1668]

**Comment by DemocracyAndScience** [comment]
When starting with cnpm run dev, an error message is reported
10: 56:07 [vike] [config] [Wrong Usage] vike pinia sets an unknown config onCreate AppPinia
Running the vike-vue example project reported the same error


// pages/+config.ts
import type { Config } from 'vike/types'
import vikeVue from 'vike-vue/config'
import vikePinia from 'vike-pinia'


export default {
  favicon: '/front/favicon.png' ,
  title: 'My Vike + Vue App',
  meta: {
    Layout: {
      env: { server: false, client: true },
    },
    Page: {
      env: { server: false, client: true },
    },
  },
  hydrationCanBeAborted: true,
  clientRouting: true,
  ssr:false,
  passToClient: ['initialStoreState', 'pageProps', 'routeParams', 'locale','user','queryParams'],
  extends: [vikeVue,vikePinia] 
} satisfies Config
 

// vite.config.ts 
import { fileURLToPath, URL } from 'node:url'
import vike from 'vike/plugin'

import { defineConfig, loadEnv } from 'vite'
import vue from '@vitejs/plugin-vue'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'
export default defineConfig(({ mode }) => {
  // 加载环境变量
  const env = loadEnv(mode, process.cwd(), '')

  // 打印环境变量以进行调试
  console.log('Loaded env:', env.VITE_BASE_URL)

  return {
    base: env.VITE_BASE_URL,
    plugins: [
      vue(),
      vike({ prerender: true }),
      AutoImport({
        resolvers: [ElementPlusResolver()],

      }),
      Components({
        resolvers: [ElementPlusResolver()],
      }),
    ],
    ssr: {
      noExternal: [/vue-i18n/, /element-plus/],
    },
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
      },
    },
  }
})

// pages/+onCreateApp.ts
// /pages/+onCreateApp.ts
// Environment: server, client

export { onCreateApp }

import type { OnCreateAppSync } from 'vike-vue'

import '@/assets/index.css'
import { createI18n } from 'vue-i18n'
import enUS from '@/locales/en-US.json'
import jaJP from '@/locales/ja-JP.json'
import zhCN from '@/locales/zh-CN.json'
import zhHG from '@/locales/zh-HK.json'

import VueDomPurifyHtml from 'vue-dompurify-html'
import 'element-plus/theme-chalk/dark/css-vars.css'
import '@/assets/dark-css-vars.css'
import { ID_INJECTION_KEY,ZINDEX_INJECTION_KEY } from 'element-plus'
import { createPinia } from 'pinia'
const onCreateApp: OnCreateAppSync = (
  pageContext
): ReturnType<OnCreateAppSync> => {
  const { app } = pageContext
  const i18n = createI18n({
    legacy: false,
    locale: 'zh-CN',
    fallbackLocale: 'en-US',
    messages: {
      'en-US': enUS,
      'ja-JP': jaJP,
      'zh-CN': zhCN,
      'zh-HK': zhHG,
      'zh-MO': zhHG,
      'zh-TW': zhHG,
      'zh-SG': zhHG,
    },
  })
  app.use(createPinia())
  app.use(i18n)
  app.provide(ID_INJECTION_KEY, {
    prefix: 1024,
    current: 0,
  })
  app.provide(ZINDEX_INJECTION_KEY, { current: 0 })
  app.use(VueDomPurifyHtml)
  console.log('onCreateApp')
}


//renderer/+onBeforeRoute.js
export default onBeforeRoute

import { LANGUAGE } from '../types/LocalStoreageConstant'

function onBeforeRoute(pageContext) {
  let language = 'zh-CN'
     
  if (pageContext.isClientSideNavigation) {
    let clientLanguage = localStorage.getItem(LANGUAGE) || navigator.language  
    if(clientLanguage){
        language = clientLanguage;
    }
  } else {
    let serverLanguage = pageContext.headers?.['accept-language'].split(',')[0]
    if(serverLanguage){
        language = serverLanguage;
    }
  }
  let urlParsed = pageContext.urlParsed ; 

  let queryParams = urlParsed.search;
  let searchLang  = queryParams.lang;
  if(searchLang ){
    if(searchLang.startsWith('zh')){
      searchLang = 'zh-CN'
    }else if(searchLang.startsWith('ja')){
      searchLang = 'ja-JP'
    }
    language = searchLang;
  }
  if (language?.startsWith('en')) {
    language = 'en-US'
  }
  console.log('locale',language)
  return {
    pageContext: {
      locale:language,
      queryParams:queryParams
    }
  }

}

**Comment by brillout** [comment]
Update `vike-vue` to its latest version. Leaving this open: we should improve the error message.
