### ISSUE TITLE
Missing "semver" in package.json

### ISSUE THREAD

**Issue by mschakulat** [vikejs/vike#1676]
### Description

In release 0.4.173 there is no "semver" dependency in the package.json but the package is imported in `vike/node/plugin/plugins/importUserCode/v1-design/assertExtensions.ts`.

As "semver" is a dependency of `@brillout/release-me` (which is a devDependency), building the application with `--prod` will fail.

**Comment by brillout** [comment]
Isn't it included in Node.js? The CI is passing so it apparently is.

**Comment by mschakulat** [comment]
As far as I can see the CI just installs all dependencies, including devDependencies so it won't fail. But using vike when installing deps with `--prod` will fail. Or am i missing something?

**Comment by brillout** [comment]
Indeed, let me fix that.

**Comment by brillout** [comment]
Fix released in `0.4.174`.

**Comment by brillout** [comment]
(Btw. in case your company is up for it: [sponsoring](https://github.com/vikejs/vike/issues/1350) makes a massive difference. Also happy to meet folks IRL in Germany.)
