### ISSUE TITLE
[Filesystem Routing] Syntax for ignoring directories

### ISSUE THREAD

**Issue by brillout** [vikejs/vike#1684]
### Description

E.g. `/pages/(marketing)/about-us/+Page.js` => `/about-us`.

So far I can't think of a better syntax than using parentheses `(marketing)`.

@Blankeos Ideas for an alternative syntax? The thing I don't like about parentheses is that they need to be escaped on Linux:

```bash
# Doesn't work:
mkdir -p pages/(marketing)/about-us/
bash: syntax error near unexpected token (
# Works:
mkdir -p pages/\(marketing\)/about-us/
```

See also:
- https://github.com/vikejs/vike/discussions/1681
- Prior discussions about what filesystem routing syntax support on various operating systems: https://github.com/vikejs/vike/issues/207

**Comment by brillout** [comment]
Released in `0.4.174-commit-d226ee7`.

**Comment by brillout** [comment]
Released in `0.4.175`.

**Comment by Blankeos** [comment]
Hi! Just read this. I see you opted for `(` and `)` anyhow. Thanks for considering the feedback!

Interesting point on `(` needing escape keys in Linux, didn't know about that. But I think it would be familiar for users migrating away from Next.

**Comment by brillout** [comment]
Yea, `__someDir__` would be nice as well. But, yea, let's stick to the Next.js syntax.
