### ISSUE TITLE
Parentheses layout overwrites parent layout for other pages

### ISSUE THREAD

**Issue by motopods** [vikejs/vike#1690]
### Description

    "vike": "0.4.175"

![layout](https://github.com/vikejs/vike/assets/58200641/ca68be77-dacf-49e8-b108-1cdee62be180)

index/+Page should use  landing/+Layout,  but it's  overwrited by (auth)/+Layout.

If we places(auth)/+Layout in (auth)/login/+Layout  with +Page in same folder, it works.

**Comment by brillout** [comment]
Let me have a look.

**Comment by brillout** [comment]
I see what's going on, let me fix this.

**Comment by brillout** [comment]
Fix released in `0.4.176`.

@motopods Btw. would your company be up for [sponsoring](https://github.com/vikejs/vike/issues/1350)? It makes a massive difference to the project!

**Comment by motopods** [comment]
@brillout Thank you for being so efficient. Based on my experience with Next.js, Remix, Solid Start, Qwik City, and Nuxt, Vike's DX is my favorite and the closest to practical use. As an individual developer, my project is still in development, and I am giving a one-time sponsorship to show my support for your team. If my project successfully goes into production, I would be happy to provide more sponsorship.

**Comment by brillout** [comment]
Thank you :green_heart: and I'm glad you're enjoying Vike.
