### ISSUE TITLE
Bug rendering after migrating to new pages format

### ISSUE THREAD

**Issue by DannyZB** [vikejs/vike#1701]
### Description

I just migrated to V2 routing format from V1 and got this error

12:26:27 PM [vike@0.4.176][request(1)][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours). at getRenderContext (/home/daniel/work/front/ui/node_modules/vike/dist/cjs/node/runtime/renderPage/renderPageAlreadyRouted.js:179:27) at renderPageAndPrepare (/home/daniel/work/front/ui/node_modules/vike/dist/cjs/node/runtime/renderPage.js:71:25) at /home/daniel/work/front/ui/node_modules/vike/dist/cjs/node/plugin/shared/getHttpRequestAsyncStore.js:71:35 at renderPage (/home/daniel/work/front/ui/node_modules/vike/dist/cjs/node/runtime/renderPage.js:50:35) at /home/daniel/work/front/ui/vite_server/index.js:31:29
logDirectly                  	log.js:53
logWithVikeTag               	log.js:19
handleAssertMsg              	loggerNotProd.js:164
logErr                       	loggerNotProd.js:97
logRuntimeError              	loggerNotProd.js:62
renderPageAndPrepare         	renderPage.js:77
Async call from await
processTicksAndRejections    	task_queues:95
Async call from await
(anonymous function)         	renderPage.js:50
run                          	async_hooks:341
(anonymous function)         	getHttp…uestAsyncStore.js:71
renderPage                   	renderPage.js:50
(anonymous function)         	index.js:31
handle                       	layer.js:95
next                         	route.js:149
dispatch                     	route.js:119
handle                       	layer.js:95
(anonymous function)         	index.js:284
param                        	index.js:365
param                        	index.js:376
process_params               	index.js:421
next                         	index.js:280
processImmediate             	timers:478
callbackTrampoline           	async_hooks:130
Async call from Immediate
init                         	inspector_async_hook:25
emitInitNative               	async_hooks:202
emitInitScript               	async_hooks:505
initAsyncResource            	timers:164
Immediate                    	timers:620
setImmediate                 	timers:302
next                         	dep-Glf1enhJ.js:42558
call                         	dep-Glf1enhJ.js:42655
next                         	dep-Glf1enhJ.js:42590
(anonymous function)         	dep-Glf1enhJ.js:53177
viteServeStaticMiddleware    	dep-Glf1enhJ.js:53296
call                         	dep-Glf1enhJ.js:42646
next                         	dep-Glf1enhJ.js:42590
viteServeRawFsMiddleware     	dep-Glf1enhJ.js:53322
call                         	dep-Glf1enhJ.js:42646
next                         	dep-Glf1enhJ.js:42590
viteTransformMiddleware      	dep-Glf1enhJ.js:63431
processTicksAndRejections    	task_queues:95
Async call from await
call                         	dep-Glf1enhJ.js:42646
next                         	dep-Glf1enhJ.js:42590
viteServePublicMiddleware    	dep-Glf1enhJ.js:53242
call                         	dep-Glf1enhJ.js:42646
next                         	dep-Glf1enhJ.js:42590
viteHMRPingMiddleware        	dep-Glf1enhJ.js:64541
call                         	dep-Glf1enhJ.js:42646
next                         	dep-Glf1enhJ.js:42590
next                         	dep-Glf1enhJ.js:42568
viteBaseMiddleware           	dep-Glf1enhJ.js:60955
call                         	dep-Glf1enhJ.js:42646
next                         	dep-Glf1enhJ.js:42590
viteCachedTransformMiddleware	dep-Glf1enhJ.js:63276
call                         	dep-Glf1enhJ.js:42646
next                         	dep-Glf1enhJ.js:42590
cors                         	dep-Glf1enhJ.js:43118
(anonymous function)         	dep-Glf1enhJ.js:43154
originCallback               	dep-Glf1enhJ.js:43144
(anonymous function)         	dep-Glf1enhJ.js:43149
optionsCallback              	dep-Glf1enhJ.js:43129
corsMiddleware               	dep-Glf1enhJ.js:43134
call                         	dep-Glf1enhJ.js:42646
next                         	dep-Glf1enhJ.js:42590
handle                       	dep-Glf1enhJ.js:42593
app                          	dep-Glf1enhJ.js:42458
handle                       	layer.js:95
trim_prefix                  	index.js:328
(anonymous function)         	index.js:286
process_params               	index.js:346
next                         	index.js:280
cookieParser                 	index.js:71
handle                       	layer.js:95
trim_prefix                  	index.js:328
(anonymous function)         	index.js:286
process_params               	index.js:346
next                         	index.js:280
expressInit                  	init.js:40
handle                       	layer.js:95
trim_prefix                  	index.js:328
(anonymous function)         	index.js:286
process_params               	index.js:346
next                         	index.js:280
query                        	query.js:45
handle                       	layer.js:95
trim_prefix                  	index.js:328
(anonymous function)         	index.js:286
process_params               	index.js:346
next                         	index.js:280
handle                       	index.js:175
handle                       	application.js:181
app                          	express.js:39
emit                         	events:513
parserOnIncoming             	_http_server:1072
parserOnHeadersComplete      	_http_common:119
Async call from HTTPINCOMINGMESSAGE
init                         	inspector_async_hook:25
emitInitNative               	async_hooks:202
connectionListenerInternal   	_http_server:633
defaultTriggerAsyncIdScope   	async_hooks:464
connectionListener           	_http_server:606
emit                         	events:513
onconnection                 	net:2025
callbackTrampoline           	async_hooks:130

**Comment by brillout** [comment]
Some pages are still using the old design. Make sure to fully migrate to the latest design.

I'll improve the error message.

**Comment by brillout** [comment]
Fix pre-released as `0.4.176-commit-03270e7`.

Thank you for sponsoring back then! :green_heart:

**Comment by DannyZB** [comment]
I will again. We release, get some budgets open and you will get a cut.
Really useful lib! great work

**Comment by brillout** [comment]
Thank you, that would be hugely appreciated 🙏
