### ISSUE TITLE
`onPrerenderStart` hook not called

### ISSUE THREAD

**Issue by FlorianCassayre** [vikejs/vike#1702]
I am in the process of migrating from plain `vike` + `react` to `vike-react`, in order to remove some of the boilerplate. My app supports prerendering (SSG) and [i18n](https://vike.dev/i18n). For that purpose I was using the `onPrerenderStart` hook, which was working fine.

However it seems that after integrating `vike-react` this `onPrerenderStart` hook stopped getting called altogether on build. I have properly configured `vike({ prerender: true })`, and even set `ssr: true` (even though it is apparently the default), but to no avail.

Here is a reproducer which reuses the example boilerplate in vike-react/examples/minimal: https://github.com/FlorianCassayre/vike-react-onPrerenderStart

The latest commit contains the actual changes and demonstrates that when running `npm run build` the hook is not called (expected behavior would be to throw an error).

It seems on the other hand that `onBeforePrerenderStart` works.

**Comment by brillout** [comment]
@FlorianCassayre Indeed, something's wrong. Let me dig into this.

**Comment by brillout** [comment]
Fix pre-released as `0.4.176-commit-1442a4a`.

Btw. in case your company is up for it, Vike is [looking for sponsors](https://github.com/vikejs/vike/issues/1350) &mdash; it makes a massive difference!

**Comment by FlorianCassayre** [comment]
Excellent, thanks for the quick fix. I'll patch my dependencies.

**Comment by FlorianCassayre** [comment]
We're not using Vike at work (yet), however I'm happy to sponsor the project as an individual.

**Comment by brillout** [comment]
Thank you, it's much appreciated :green_heart:

**Comment by crummy** [comment]
This fixed a problem I was having (thank you!) but causes npm errors because I use `vike-react` which needs `peer vike@">=0.4.173"`. How often are Vike releases?

**Comment by FlorianCassayre** [comment]
I use `--force` for the time being, I think I read somewhere that you could not override peer dependencies coming from monorepositories. You can also use `patch-package` to apply the one-liner fix.
