### ISSUE TITLE
Hot reloading of CSS modules

### ISSUE THREAD

**Issue by davenquinn** [vikejs/vike#1728]
### Description

Hot reloading of CSS modules does not appear to work properly in Vike using React. When CSS modules are changed, the entire page reloads rather than applying the new styles. This is not consistent with behavior for Javascript/Typescript modules (which do properly reload) or handing of CSS modules in Vite without ssr.

How to replicate:
1. Scaffold a testing app with `yarn @batijs/cli --react` or similar
2. Add a file `pages/index/main.module.css` with the following contents:
```
.test {
    color: red;
    margin: 3em;
}
```
3. Alter `pages/index/+Page.tsx` to add the stylesheet:
```
import React from "react";
import { Counter } from "./Counter.js";
import styles from "./main.module.css";

export default function Page() {
  return (
    <>
      <h1 className={styles.test}>My Vike app</h1>
      This page is:
      <ul>
        <li>Rendered to HTML.</li>
        <li>
          Interactive. <Counter />
        </li>
      </ul>
    </>
  );
}
```
4. Change the style somehow. It should report `hmr update /pages/index/+Page.tsx`
5. **Key step**: restart the Vike server.
6. Change the style again. It now reports `page reload pages/index/main.module.css` and the page fully reloads

In Vike, changing a CSS style results in 
<img width="524" alt="image" src="https://github.com/vikejs/vike/assets/1537910/761e09a0-1918-4593-9b99-51d3322f7b61">

In Vite without SSR (`yarn dlx create-vite` and similar updates to above), style updates result in:
<img width="416" alt="image" src="https://github.com/vikejs/vike/assets/1537910/1a96b504-fd04-43a9-b646-a83834b680d8">

Weirdly, HMR works properly when the CSS module has just been added in the same session.

**Comment by brillout** [comment]
See https://github.com/vikejs/vike/issues/1127.
