### ISSUE TITLE
Logger assumes string

### ISSUE THREAD

**Issue by vrzlev** [vikejs/vike#1738]
### Description

In 

https://github.com/vikejs/vike/blob/b272e325909bcc0a012ba5c9d893992671656f88/vike/node/plugin/shared/loggerVite.ts#L17-L29

`msg` is assumed to be string, and trimmed.

Using vavite and ran into this line:

https://github.com/cyco130/vavite/blob/3347bfbbf92127cb1a220ce02d65761967e1add5/packages/reloader/src/index.ts#L288

Passing a `TypeError` object produces another error, and the original one is 'silenced' in the output.  

Arguably this is a bug on vavite's side, but ideally Vike's logger plays it safe too.

**Comment by brillout** [comment]
Makes sense. Up for a PR?

**Comment by brillout** [comment]
Going ahead and closing as it's more of a vavite issue, but PR welcome!
