### ISSUE TITLE
basic src/pages/ structure is weirdly converted to domain driven structure

### ISSUE THREAD

**Issue by nathanredblur** [vikejs/vike#1761]
### Description

I have a single page project with the next structure 
![CleanShot 2024-07-22 at 18 54 09](https://github.com/user-attachments/assets/63f61a86-5d1a-4fe3-af7b-96c2dda0ec3f)

but when I try to open my index `/` page, the page is not found.
and I get this message

```
6:35:47 PM [vike][request(1)] URL / doesn't match the route of any of your pages:
┌────────┬──────────────────┬───────────────────┐
│ ROUTE  │ TYPE             │ DEFINED BY        │
├────────┼──────────────────┼───────────────────┤
│ /Pages │ Filesystem Route │ /src/Pages/index/ │
└────────┴──────────────────┴───────────────────┘
See https://vike.dev/routing for more information about routing.
6:35:47 PM [vike][request(1)] HTTP response / null
```

the only way to open my page is in `/Pages` but I don't know why.

**Comment by brillout** [comment]
That's weird indeed: any idea why the directory name picked by Node.js is `Pages` instead of `pages`? Can you provide a reproduction?

**Comment by pdanpdan** [comment]
Are you on mac or windows? Maybe the name of the folder you have is `Pages` with capital `P`?

**Comment by brillout** [comment]
Let's re-open once we get more information on this. So far I'm inclined to think OP named his directory `Pages`.
