### ISSUE TITLE
I got error, but no more info for bugs.

### ISSUE THREAD

**Issue by Nelie-Taylor** [vikejs/vike#1763]
### Description

Hi, Thank you for greate framework.
![image](https://github.com/user-attachments/assets/23ae120a-7e0d-4e42-b8e9-d22dc0b876b1)
I got error, but i don't know what is wrong, please help me.
Thank you.

**Comment by Nelie-Taylor** [comment]
I upgrade from 
```
 "vike": "^0.4.172",
  "vike-react": "^0.4.11",
  "vite": "^5.2.12"
```
To
```
"vike": "^0.4.181",
"vike-react": "^0.4.18",
"vite": "^5.3.4"
```

**Comment by brillout** [comment]
Inject the following before the line `115` of `node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/assertExtensions.js` and report back.

```diff
+       console.log('packageJson', packageJson);
+       console.log('version', version)
+       console.log('name', name)
        assert(typeof version === 'string');
```

**Comment by Nelie-Taylor** [comment]
> Inject the following before the line `115` of `node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/assertExtensions.js` and report back.
> 
> ```diff
> +       console.log('packageJson', packageJson);
> +       console.log('version', version)
> +       console.log('name', name)
>         assert(typeof version === 'string');
> ```

Thank you for reply.
I find error with miss version.

**Comment by brillout** [comment]
Can you report back the console.log() results? Vike should show a better error message.
