### ISSUE TITLE
vite-plugin-ssr Bug

### ISSUE THREAD

**Issue by bpooja0508** [vikejs/vike#1765]
### Description

Error: [vite-plugin-ssr@0.4.112][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at getPageContextSerializedInHtml.js?v=250ba1d5:38:9
    at Array.map (<anonymous>)
    at getPageContextsSerializedInHtml (getPageContextSerializedInHtml.js?v=250ba1d5:36:41)
    at getPageContexts (getPageContext.js?v=250ba1d5:20:26)
    at hydrate (entry.js:15:40)
    at entry.js:9:1

**Comment by brillout** [comment]
Upgrade to the latest version of Vike. I'll re-open if you still the issue.
