### ISSUE TITLE
Infinite reruns in watch mode using tsx for Vike 

### ISSUE THREAD

**Issue by fortezhuo** [vikejs/vike#1775]
### Description

It's not a bug. Just filing this issue for further information.

If someone using vike, vite and [tsx](https://github.com/privatenumber/tsx) for development and got infinite reruns in watch mode.  https://github.com/privatenumber/tsx/issues/149

Here is a solution, just set package json script

```
dev: "tsx watch --ignore vite.config.ts.timestamp-*.mjs --ignore **/*/+config.ts.build-*.mjs ./src/server/index.ts"
```
I hope you find this information useful.

**Comment by brillout** [comment]
Thank you! FYI we recently released [`vike-node`](https://github.com/vikejs/vike-node), so you don't have to use tsx anymore.
