### ISSUE TITLE
baseAssets affecting app base in vite dev mode

### ISSUE THREAD

**Issue by kevinwarne** [vikejs/vike#1790]
### Description

Hi @brillout I am using the [baseAssets](https://vike.dev/base-url#baseassets) configuration in the docs to add a prefix where all my application assets will be requested from. Unfortunately when I use this configuration and run the app in dev mode with the `vite` command. The node server expects the app base path to always have that prefix.

I have this replicated in the `base-url-cdn` vike example by adding the package script `"serve": "vite"` and running `npm run serve`.

I currently have a work around in place that utilizes a different proxy server to add in the baseAsset prefix on page requests and then I strip it out when prerendering in the +onRenderHtml.ts hook. So this isn't necessarily a pressing issue for me, but I wanted to get ahead of it in case a future version was planning to fix the baseAssets option.

As always thank you for your help and keep up the fantastic work!

**Comment by brillout** [comment]
You can apply the `baseAssets` setting only for production, let me update the docs to mention that.

> As always thank you for your help and keep up the fantastic work!

Thanks! (Sponsoring welcome in case that's something your company would be up for :).)

**Comment by brillout** [comment]
Indeed `baseAssets` should, by default, only be applied in production: https://github.com/vikejs/vike/issues/1794.
