### ISSUE TITLE
Cannot declare nested `meta` when using `extends` 

### ISSUE THREAD

**Issue by dajinchu** [vikejs/vike#1802]
### Description

Declaring a `meta` config inside a specific directory doesn't work when `extends` is in use.

[reproduction](https://github.com/vikejs/vike/compare/main...dajinchu:vite-plugin-ssr:dc/nested-meta-with-extends?expand=1)

Compare with [when `extends` is not used](https://github.com/vikejs/vike/blob/main/examples/path-aliases/pages/about/%2Bconfig.js) and it appears to work fine.

I'm not sure that [`extends` inheritance](https://vike.dev/extends#inheritance) works either anymore? There are no examples of it to repro easily, but in [Bifrost](https://github.com/Alignable/bifrost) we rely on being able to have different config structures in different folders, and that doesn't seem to work.

### Probably unrelated
It also appears that each extension can only export one config now, with the `name` field set to the package name? Is this an intended restriction? I can work around it in Bifrost, but we currently rely on exporting 4 different configs. I could probably move 3 of them into a global config.

**Comment by brillout** [comment]
> ### Description
> Declaring a `meta` config inside a specific directory doesn't work when `extends` is in use.
> 
> [reproduction](https://github.com/vikejs/vike/compare/main...dajinchu:vite-plugin-ssr:dc/nested-meta-with-extends?expand=1)

I could reproduce indeed. I'll have a look it.

> I'm not sure that [`extends` inheritance](https://vike.dev/extends#inheritance) works either anymore? There are no examples of it to repro easily, but in [Bifrost](https://github.com/Alignable/bifrost) we rely on being able to have different config structures in different folders, and that doesn't seem to work.

Does it used to work while it doesn't anymore upon upgrading Vike?

> ### Probably unrelated
> It also appears that each extension can only export one config now, with the `name` field set to the package name? Is this an intended restriction? I can work around it in Bifrost, but we currently rely on exporting 4 different configs. I could probably move 3 of them into a global config.

Yes, it is an intended (and beneficial) restriction. What's your rationale for having multiple extensions in one package?

I'm currently abroad so I'll be slower than usual.

**Comment by dajinchu** [comment]
> Does it used to work while it doesn't anymore upon upgrading Vike?

Yeah, I can verify that it worked in Vike 0.4.168

> What's your rationale for having multiple extensions in one package?

Bifrost lets you mix Vike pages with proxied pages to a Turbolinks/Rails server, so we let you configure your proxy via a separate config/route. 

I think I can work under the new restriction by moving the proxy settings to the global config. Will give it a shot.

BTW we would ideally be able to add routes/pages from an extension - is this possible?

> I'm currently abroad so I'll be slower than usual.

No worries, thanks for the response.

**Comment by brillout** [comment]
Fix released in `0.4.189`. Apologies for delay.

Let me know if you still run into any issues with config inheritance.

> Bifrost lets you mix Vike pages with proxied pages to a Turbolinks/Rails server, so we let you setup your proxy routes via a separate config.
>
> I think I can work under the new restriction by moving the proxy settings to the global config. Will give it a shot.

Would it be possible to have one "big Vike extension" while pages use settings to cherry pick what they need? Or is there a reason you'd rather not do that and prefer breaking it down into multiple Vike extensions?

> BTW we would ideally be able to add routes/pages from an extension - is this possible?

Yes, it's very much on the radar. Although we're focusing on releasing the `v1.0.0` and rehauling Vike's marketing at the moment, so it will take a little while until we get there. It will happen though, e.g. we'll need it ourselves as we plan to create extensions that create admin pages.
