### ISSUE TITLE
throw redirect() infinite loop

### ISSUE THREAD

**Issue by tathje** [vikejs/vike#1820]
### Description

Hello @brillout. I create **locale** parameters and store the language in a cookie and use **throw redirect** to redirect using the stored locale. The first time, it worked correctly but I saw my redirect loop error when I switched languages.

<img width="1032" alt="Screenshot 2024-08-21 at 23 52 39" src="https://github.com/user-attachments/assets/b4aed963-1e27-428d-a0c8-ce9c4005f095">
Here is my log in **vike/node/runtime/renderPage/createHttpResponseObject/assertNoInfiniteHttpRedirect.ts**

> "vike": "^0.4.191"

Thanks for the great project!

**Comment by brillout** [comment]
What makes you think it's a bug? Closing, but let's re-open if it's potentially a bug.
