### ISSUE TITLE
All `+route` are triggered

### ISSUE THREAD

**Issue by rtritto** [vikejs/vike#1858]
### Description

When you navigate on a page, all [route](https://vike.dev/route) hooks are triggered.

## Reproduction
1. `git clone https://github.com/rtritto/template-vike-solid-daisyui.git`
2. `cd template-vike-solid-daisyui`
3. `git checkout bug-trigger-route`
4. `yarn`
5. `yarn dev`
6. Navigate to `http://localhost:3000`
7. Check logs:

    ```console
    route testroute1
    route testroute2
    ```

**Comment by brillout** [comment]
https://vike.dev/route-function#lightweight-fast

**Comment by rtritto** [comment]
Using filesystem routing, where I can validate route parameters?

**Comment by brillout** [comment]
https://brillout.github.io/rules#try
