### ISSUE TITLE
[commonjs--resolver] [vike][Wrong Usage] Client-only file /app/components/LangaugeSelect.client.tsx (https://vike.dev/file-env) imported on the server-side by /app/components/Footer.tsx

### ISSUE THREAD

**Issue by NotNullDev** [vikejs/vike#1861]
### Description

I don't know if it's a bug or I missunderstood how *.client.ts files work.

I wanted to move my remix app to vike, and in remix this works fine.
I am using this LangaugeSelect component inside of Footer, which is rendered inside DefaultLayout.tsx.

In remix I used little helper `<ClientOnly><LanguageSelect/></ClientOnly>` which returned nothing on the server and component on the client.

In vike I am unable to build the app with same setup. I also tried clientOnly(() => ...), and react lazy + suspense, but the error message is still here.

If it may be a bug then I can provide more informations.

**Comment by brillout** [comment]
Minimal reproduction welcome.

**Comment by NotNullDev** [comment]
https://github.com/NotNullDev/vike-client-component/commit/a7027a3aa8fffabeae973bf9a1ca4ce255fae3fd

**Comment by NotNullDev** [comment]
Can vike support importing client modules in the same way as remix does?

https://remix.run/docs/en/main/file-conventions/-client
https://github.com/remix-run/remix/blob/7dece0e4db691fc9e5dfce27ad6373c46b6ef56c/packages/remix-dev/vite/plugin.ts#L1570

Right now, as far as I understand, it's simply not possible to import .client in ssr mode

https://github.com/vikejs/vike/blob/d84dc798eac0fe5b52e642111650f3bab9f02137/vike/node/plugin/plugins/fileEnv.ts#L61C9-L61C14
https://github.com/vikejs/vike/blob/d84dc798eac0fe5b52e642111650f3bab9f02137/vike/node/plugin/plugins/fileEnv.ts#L109

**Comment by brillout** [comment]
I could reproduce indeed, let me me fix this. In the meantime you can use `clientOnly()` without the `.client.js` suffix.

**Comment by brillout** [comment]
> let me me fix this

ETA next week. In the meantime, feel free to let me know if not using `.client.js` is an issue for you.

**Comment by brillout** [comment]
Fix pre-released as `0.4.195-commit-f7e91ba`.
