### ISSUE TITLE
[build] I use Vite's Javascript API to build, and it will not build the SSR bundle. 

### ISSUE THREAD

**Issue by AliceZ413** [vikejs/vike#1876]
### Description

Hi, I am being troubled by an issue when using Vike.
I plan to use the [build](https://vitejs.dev/guide/api-javascript#build) method from the **Vite JavaScript API** to implement Vite building as follows code.
```
import { build } from 'vite';
await build();
```
However, after executing `build()`, I can only get one 'client' result, whereas there should normally be a 'ssr' result as well.

> when use the Vite JavaScript API 
> <img width="703" alt="image" src="https://github.com/user-attachments/assets/51cdd6bb-752d-4858-a84b-2c4e1e58be03">

> when use `npx vite build`
> <img width="712" alt="image" src="https://github.com/user-attachments/assets/4ad4af72-a38a-4480-b889-a61ec47cda5b">

I can confirm that the Vite configuration is correct, and the Vike plugin is included, but I still can't obtain the SSR bundle through the Vite JavaScript API. I think this might still be an issue with Vike.

**Comment by brillout** [comment]
You've to run Vite twice: one for the client-side code and a second time for the server-side code.
