### ISSUE TITLE
Docker multi-stage builds vs vite-plugin-server-entry

### ISSUE THREAD

**Issue by roschaefer** [vikejs/vike#1877]
### Description

We were blocked to update vike from version `0.4.176` onwards because if we run our app from within a Docker image, it would display "An error occurred."

The logs in the docker container would show:
```
presenter-1  | Error: [@brillout/vite-plugin-server-entry@0.4.12][Wrong Usage] Cannot find server entry. (Re-)build your app and try again. If you still get this error, then you may need to manually import the server entry, see https://github.com/brillout/vite-plugin-server-entry#manual-import
presenter-1  |     at importServerEntry (/app/node_modules/@brillout/vite-plugin-server-entry/dist/runtime/importServerEntry.js:39:29)
presenter-1  |     at async loadImportBuild (/app/node_modules/vike/dist/cjs/node/runtime/globalContext/loadImportBuild.js:15:9)
```

We figured out that we have to manually copy a file from `node_modules` in a multi-stage docker build:
```
COPY --from=build ${DOCKER_WORKDIR}/node_modules/@brillout/vite-plugin-server-entry/dist/runtime/autoImporter.js ./node_modules/@brillout/vite-plugin-server-entry/dist/runtime/autoImporter.js
```

Here's our PR changing the relevant `Dockerfile`: https://github.com/dreammall-earth/dreammall.earth/pull/2018

What is the suggested workflow with `vike` running inside a docker image?

**Comment by brillout** [comment]
Indeed, that should work. You can also manually import `dist/server/entry.js`. I've improved the section https://github.com/brillout/vite-plugin-server-entry#manual-import &mdash; let me know if you still have questions.

Btw. in case your company is up for it, we're looking for sponsors (#1350).
