### ISSUE TITLE
hashchange not triggered

### ISSUE THREAD

**Issue by flyerH** [vikejs/vike#1883]
This is repo: https://github.com/flyerH/vike-vue-example
Run and open http://localhost:3000/a

<img src="https://github.com/user-attachments/assets/aca935ac-fe6e-4dcb-af71-635a9d1043ee" width=50%>

When use the client routing, If you click the short link, the hashchange event will not be triggered.
I use this feature to jump from page A to page B and automatically locate the anchor point, and avoid full refreshing the page through client routing.

**Comment by brillout** [comment]
Fix pre-released as `vike@0.4.195-commit-3f77496`.

**Comment by flyerH** [comment]
It's work! Thank you~
