### ISSUE TITLE
[vite-plugin-ssr:buildConfig] [vite-plugin-ssr@0.4.142][Bug] You stumbled upon a bug in vite-plugin-ssr's source code

### ISSUE THREAD

**Issue by renzhanguo** [vikejs/vike#1893]
### Description

  "vite": "^5.4.7", 
 "vite-plugin-ssr": "^0.4.142",

@joymeet/app:build: ✓ 993 modules transformed.
@joymeet/app:build: rendering chunks...
@joymeet/app:build: computing gzip size...
@joymeet/app:build: x Build failed in 14.44s
@joymeet/app:build: error during build:
@joymeet/app:build: [vite-plugin-ssr:buildConfig] [vite-plugin-ssr@0.4.142][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error; a maintainer will fix the bug (usually under 24 hours).
@joymeet/app:build:     at Object.writeBundle (file:///Users/mac/Desktop/project/xj-c/node_modules/.pnpm/vite-plugin-ssr@0.4.142_vite@5.4.7/node_modules/vite-plugin-ssr/dist/esm/node/plugin/plugins/buildConfig.js:54:17)
@joymeet/app:build:     at file:///Users/mac/Desktop/project/xj-c/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:19936:40
@joymeet/app:build:     at async Promise.all (index 2)
@joymeet/app:build:     at PluginDriver.hookParallel (file:///Users/mac/Desktop/project/xj-c/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:19864:9)
@joymeet/app:build:     at file:///Users/mac/Desktop/project/xj-c/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:20860:13
@joymeet/app:build:     at catchUnfinishedHookActions (file:///Users/mac/Desktop/project/xj-c/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:20282:16)
@joymeet/app:build:     at build (file:///Users/mac/Desktop/project/xj-c/node_modules/.pnpm/vite@5.4.7_@types+node@18.15.11_less@4.1.3_terser@5.16.9/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:65391:16)
@joymeet/app:build:     at CAC.<anonymous> (file:///Users/mac/Desktop/project/xj-c/node_modules/.pnpm/vite@5.4.7_@types+node@18.15.11_less@4.1.3_terser@5.16.9/node_modules/vite/dist/node/cli.js:828:5)
@joymeet/app:build:  ELIFECYCLE  Command failed with exit code 1.
@joymeet/app:build: ERROR: command finished with error: command (/Users/mac/Desktop/project/xj-c/packages/app) pnpm run build exited (1)
command (/Users/mac/Desktop/project/xj-c/packages/app) pnpm run build exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    15.743s

**Comment by brillout** [comment]
Same: https://github.com/vikejs/vike/issues/1891#issuecomment-2367298475.
