### ISSUE TITLE
Safari Only - Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating ‘e.configValues’) at renderPageClientSide:37

### ISSUE THREAD

**Issue by snake-py** [vikejs/vike#1900]
### Description

Hey,

I am unsure if this is really a Vike bug. I am seeing very recently in our Vike/React application that JS execution is completely blocked on Safari 17.7, and only in our deployed version (S3 and cloudfront). It is working fine on the same device using chrome. 
The vike vertsion we have installed is “^0.4.177-commit-f4a92e0". I am seeing in the console only 

```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating ‘e.configValues’) at renderPageClientSide:37
```

**Comment by brillout** [comment]
Can you update to the latest version and, if you still get this, then copy-paste the line at `renderPageClientSide:37` where the error originates from. I'll re-open then.
