### ISSUE TITLE
[vike@0.4.198][Bug] You stumbled upon a Vike bug

### ISSUE THREAD

**Issue by snake-py** [vikejs/vike#1936]
### Description

Sentry shows me this: 

![image](https://github.com/user-attachments/assets/7ca4a875-4c54-49e2-bf84-390b09269d66)

But I don't think that this is enough information, I just wanted to leave it here for documentation reason, if I can gather more info I will update here.

**Comment by brillout** [comment]
It has been fixed in 199.
