### ISSUE TITLE
Case-Insensitive File Collision after Cloning Repository

### ISSUE THREAD

**Issue by neutrino84** [vikejs/vike#1942]
## Summary

When cloning the repository `vikejs/vike` on a macOS system (or any case-insensitive filesystem), there is a collision between two files due to case differences in their paths. This causes Git to behave unexpectedly, leading to an unclean working directory as one of the conflicting files is modified right after cloning. The issue only manifests on case-insensitive filesystems.

## Steps to Reproduce

1. Clone the `vikejs/vike` repository:
   ```bash
   git clone https://github.com/vikejs/vike.git
   ```

2. After the repository is cloned, Git shows a warning about case-insensitive paths:
   ```bash
   warning: the following paths have collided (e.g. case-sensitive paths
   on a case-insensitive filesystem) and only one from the same
   colliding group is in the working tree:

     'docs/pages/Head/+Page.mdx'
     'docs/pages/head/+Page.mdx'
   ```
## Environment

- **Operating System:** macOS (case-insensitive filesystem)  
- **Git version:** Example `git version 2.x.x`  
- **Repository:** https://github.com/vikejs/vike

## Possible Solution

One potential solution may be renaming one of the conflicting files to avoid case differences—especially in directories like `docs/pages/Head` and `docs/pages/head` where the case distinction is critical on case-sensitive systems but problematic on case-insensitive systems.

Alternatively, the repository could include a note in the README or contribution guidelines regarding this issue, suggesting that certain files might not work properly on case-insensitive environments.

**Comment by brillout** [comment]
Let me know if you still run into issues.
