### ISSUE TITLE
docpress api key is exposed

### ISSUE THREAD

**Issue by snake-py** [vikejs/vike#1958]
### Description

Hey while going through the repo I saw that the api key is exposed in [docs/docpress.confgi.ts:18](https://github.dev/vikejs/vike/blob/main/docs/docpress.config.ts). I just wasn't sure if this is fine wanted to point that out.

**Comment by brillout** [comment]
Doesn't it end being public anyways because it's included in the client-side JS? Let's re-open if I'm wrong.
