### ISSUE TITLE
New Vike bug 🤷🏽‍♀️

### ISSUE THREAD

**Issue by 4519025294881167** [vikejs/vike#1984]
### Description

function o(e, t) {
    if (e) return;
    const n = (() => {
        if (!t) return null;
        const s = typeof t == "string" ? t : JSON.stringify(t);
        return b.dim(`Debug info (for Vike maintainers; you can ignore this): ${s}`)
    })();
    let r = ["You stumbled upon a Vike bug.", `Go to ${b.blue("https://github.com/vikejs/vike/issues/new")} and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).`, n].filter(Boolean).join(" ");
    r = I(r), r = C(r, "Bug"), r = L(r, !0);
    const i = U(r, H);
    throw S.onBeforeLog?.(), i
}

**Comment by brillout** [comment]
Can you post the error message and stack? I'll re-open then.
