### ISSUE TITLE
Virtual files error

### ISSUE THREAD

**Issue by jandolezal71** [vikejs/vike#1985]
### Description

```
8:25:57 PM [vike@0.4.201][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at isVirtualFileId (/app-deck/node_modules/vike/dist/esm/utils/virtual-files.js:13:4)
    at resolveId (/app-deck/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/index.js:34:16)
    at /app-deck/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49015:16
    at processTicksAndRejections (native)
```

**Comment by brillout** [comment]
Try with the latest version. I'll re-open if you still get the error.

**Comment by jandolezal71** [comment]
> Try with the latest version. I'll re-open if you still get the error.

Hi! Thanks for fast response. Got same error with `vike@0.4.204`

```
bun 1.1.33
```

**Comment by brillout** [comment]
Do you also get this with Node.js?

**Comment by jandolezal71** [comment]
I checked my commits and fault is comming from setting "baseUrl" in `tsconfig.json`.

When i add `baseUrl: "./"`, this error will appear.

Full `tsconfig.json`:

```json
{
  "compilerOptions": {
    "strict": true,
    "allowJs": true,
    "checkJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "baseUrl": "./",
    "module": "ESNext",
    "noEmit": true,
    "moduleDetection": "force",
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noUncheckedIndexedAccess": true,
    "noPropertyAccessFromIndexSignature": true,
    "verbatimModuleSyntax": true,
    "moduleResolution": "Bundler",
    "target": "ES2022",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "paths": {
      "@/*": ["./src/*"]
    },
    "types": ["bun-types", "vite/client", "vike-react"],
    "jsx": "preserve",
    "jsxImportSource": "react"
  },
  "exclude": ["dist"]
}
```

**Comment by brillout** [comment]
Yea, I ain't sure Vite supports that. I cannot reproduce. Reproduction welcome and I'll improve Vike's error message.

**Comment by jandolezal71** [comment]
> Yea, I ain't sure Vite supports that. I cannot reproduce. Reproduction welcome and I'll improve Vike's error message.

Well, `vite` itself no, but with [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths) plugin, what  i use, it does (aswell as others paths) https://github.com/aleclarson/vite-tsconfig-paths?tab=readme-ov-file#baseurl

**Comment by brillout** [comment]
I see, reproduction welcome and I'll have a look at it. Although it's likely a non-goal to support `baseUrl` but let's see maybe it's worth it.

**Comment by jandolezal71** [comment]
Hi, i created a repro repo for you

https://github.com/jandolezal71/vike-bug-repro-1985

**Comment by brillout** [comment]
I could reproduce. I double checked and, indeed, it isn't a trivial change for supporting it. I improved the error message.

If it's okay with you I'll leave it like that. But feel free to push back and elaborate why you want/need to be able to use `baseUrl`.

**Comment by jandolezal71** [comment]
I think impoved error message would be good enough. I don't need `baseUrl` (using paths anyway). Just that error message could be cryptic for some users.

**Comment by brillout** [comment]
Agreed; [Vike now shows a helpful error message](https://github.com/vikejs/vike/commit/796c72f44e4ad6a21a78f0ba5fc75311bf52bb4f).
