### ISSUE TITLE
Get an error from sentry: [vike@0.4.181][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours). Debug info (for Vike maintainers; you can ignore this): about:blank

### ISSUE THREAD

**Issue by panzuhong** [vikejs/vike#1995]
### Description

[vike@0.4.181][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours). Debug info (for Vike maintainers; you can ignore this): about:blank
It appears in production, if it's okay in latest version

**Comment by brillout** [comment]
Let's re-open if you still get this with the latest version. And please always include the error stack.
