### ISSUE TITLE
[vike-solid]: add setData export for useData hook

### ISSUE THREAD

**Issue by rtritto** [vikejs/vike#1998]
### Description / use case

First retrieving initial data on `+data` _page hook_.
On the rendered page, _data_ is displayed.
_Data_ needs to be updated with a button.

Example:

```ts
// /utils/getData.ts

export default async () => { ... }

```

```ts
// /pages/user/+data.ts

import getData from '/utils/getData'

export const data = async (pageContext) => {
  const data = await getData()
  return data
}
```

```tsx
// /pages/user/+Page.ts

import { useData } from 'vike-solid/useData'
import getData from '/utils/getData'

export const Page = () => {
  const [data, setData] = useData()
  
  return (
    <>
      <button onClick={async () => {
        const newData = await getData()
        setData(newData)
      }}>
        Get updated User
      </button>

      {data}
    </>
  )
}
```

### Changes

[vike-solid/hooks/useData.tsx](https://github.com/vikejs/vike-solid/blob/3d45717aa88f639493898e18a8044158d06af6b2/packages/vike-solid/hooks/useData.tsx)

```diff
function useData<Data>(): Data {
  const pageContext = usePageContext() as any;

  // sub store to keep reactivity https://github.com/vikejs/vike-solid/issues/114
  const [data, setData] = createStore(pageContext?.data);

  createEffect(() => {
    setData(pageContext?.data);
  });

-  return data;
+  return [data, setData];
}
```

**Comment by brillout** [comment]
So far it isn't a goal to have built-in data management (use a state management library instead).

**Comment by rtritto** [comment]
FYI @magne4000

**Comment by rtritto** [comment]
> So far it isn't a goal to have built-in data management (use a state management library instead).

@brillout it's a simple re-export, imo there isn't any sense to create a new object.
Also the keyword `use` is usually used as standard for hooks that export the array with getter and setter ([reference1](https://jotai.org/docs/core/use-atom); [reference2](https://recoiljs.org/docs/api-reference/core/useRecoilState)).

**Comment by brillout** [comment]
It isn't as simple as you think.

**Comment by magne4000** [comment]
`useData` should only be used for data coming straight from `+data` hook IMO.
If you start to mix that with user data, you will have discrepancies.
For instance, upon client-side navigation, your data will be erased by `+data` hook. Perhaps that's what you want, perhaps that's not.

You can circumvent those issues by having a second store that you manage, and reconcile the 2 stores in a third one. That way you should control everything that you need.

**Comment by rtritto** [comment]
@magne4000 @brillout Any idea to reconsider this feature?

I'm using the `solid-jotai` dependency to share signals through atoms. I have the [issue](https://github.com/wobsoriano/solid-jotai/issues/11) where the initial values of atoms are hydrated before first render ([HydrateAtoms](https://github.com/templates-ecosystem/template-vike-solid-daisyui-hono/blob/7071b46dee66799acefbac149c83e09456a6d1f8/src/pages/%40id/HydrateAtoms.tsx) component) but, using a link to a new page, I can't re-render the `Provider` component when _data_ (from `useData`) is changed on the new page.

The `useData` hook already handle the store context and having also the export of `setData`.

So this feature will be a zero-code (drop-in replacement already implemented and free to use) to configure and use the shared store (through `useData` hook) in the context of the page.

Maybe the [issue](https://github.com/wobsoriano/solid-jotai/issues/11) have no solution or a simple solution  ([source](https://github.com/wobsoriano/solid-jotai/issues/11#issuecomment-2727695660)).
So would be better to use _directly_ the `useData` hook instead of `solid-jotai`.

On my test, I have no issue with a patched `vike-solid`:
- [vike-solid/hooks/useData.tsx](https://github.com/vikejs/vike-solid/blob/3d45717aa88f639493898e18a8044158d06af6b2/packages/vike-solid/hooks/useData.tsx)

    ```diff
    function useData<Data>(): Data {
      const pageContext = usePageContext() as any;
    
      // sub store to keep reactivity https://github.com/vikejs/vike-solid/issues/114
      const [data, setData] = createStore(pageContext?.data);
    
      createEffect(() => {
        setData(pageContext?.data);
      });
    
    -  return data;
    +  return [data, setData];
    }
    ```

FYI @wobsoriano @phonzammi @Blankeos @atk

**Comment by magne4000** [comment]
I still think that `useData` should not export its setter.
@rtritto What I would advise would be to create your own copy of `useData` for this particular need.

**Comment by rtritto** [comment]
@magne4000 Any updates to see this feature?
I'm using this feature a lot on different projects.

Simple use case:

```tsx
import { useData } from 'vike-solid/useData'
import getData from '/utils/getData'

const ShowData = (props) => {
  return <>{props.data}</>
}

const SetData = (props) => {
  return (
    <button onClick={async () => {
      const newData = await getData()
      props.setData(newData)
    }}>
      Update Data
    </button>
  )
}

export const Page = () => {
  const [data, setData] = useData()
  
  return (
    <>
      <ShowData data={data} />

      <SetData setData={setData} />
    </>
  )
}
```

Edit:
### Diff
```diff
diff --git a/dist/hooks/useData.d.ts b/dist/hooks/useData.d.ts
index ccf9484ed04ac8b46622160f2496172dc5a9063a..24056240e094719be1a3b347ea68a049c338877b 100644
--- a/dist/hooks/useData.d.ts
+++ b/dist/hooks/useData.d.ts
@@ -1,9 +1,11 @@
+import { SetStoreFunction } from 'solid-js/store';
+
 /** Access `pageContext.data` from any SolidJS component
  *
  * See
  * - https://vike.dev/data
  * - https://vike.dev/pageContext-anywhere
  */
-declare function useData<Data>(): Data;
+declare function useData<Data>(): [Data, SetStoreFunction<Data>];
 
 export { useData };
diff --git a/dist/hooks/useData.js b/dist/hooks/useData.js
index 1ac40d76b3b311c5b6871fe4ba23cfb906c8930c..3367e7623054e9d4961399e3a62e47eea807a691 100644
--- a/dist/hooks/useData.js
+++ b/dist/hooks/useData.js
@@ -17,7 +17,7 @@ function useData() {
   createEffect(() => {
     setData(pageContext?.data);
   });
-  return data;
+  return [data, setData];
 }
 
 export { useData };
```

**Comment by brillout** [comment]
Personally, I ain't categorically against going in that direction. But we currently have higher priorities.

In principle, I agree that there might be some DX simplification to be found in the intial data + state management area, but so far I think using `useData()` only for initial data is an acceptable DX for now.

@rtritto Keep in mind that we have a lot of priorities, thank you!

**Comment by brillout** [comment]
@rtritto I'm actually increasingly liking your idea... WDYT of [this](https://github.com/facebook/react/issues/24669#issuecomment-3763672850) and the following?

```tsx
// MovieList.tsx

import { useState } from 'telefunc/react'
import { onMovieFetch } from './MovieList.telefunc.ts'

function MovieList() {
  return (
    <div>
      <p>List of movies:</p>
      <Suspense fallback={<p>Loading...</p>}>
        <List />
      </Suspense>
    </div>
  )
}

function List() {
  // Note how useState() is imported from telefunc/react
  const [movies, setMovies] = useState(
    // Async Initial data
    async () => await onMovieFetch(),
    // Dependency array like useEffect()
    []
  )
  return (
    <ul>
      {movies.forEach((movie) => (
        <li>{movie.title} ({movie.release_date})</li>
      ))}
      <button onClick={async () => setMovies(await onMovieFetch())}>
        Refetch
      </button>
    </ul>
  )
}
```

**Comment by rtritto** [comment]
@brillout the `useState` is another use case where you have data to fetch (e.g. list of movies).
In my use case, the `data` (provided by the _useData_ function) has been initialized server side (`+data` hook) with initial fetched data (e.g. list of movies) and other informations/configurations.
The [implementation](https://github.com/vikejs/vike-solid/blob/7b99674292c5a2e7baadf6928b9fa7c9e5ebe4e8/packages/vike-solid/hooks/useData.tsx#L18) of _useData_ hook is a *store* that can have the setter like _setData_ (see [documentation](https://docs.solidjs.com/concepts/stores) for examples and usages).
You can think about a *store* (multiple _signal_/_state_ all in once, object key-value of _signal_/_state_) that is used with getter and setter by components.

**Comment by brillout** [comment]
My point is that it's basically all just a state with data being the initial value. That's why I'm inclined to simply call it `useState(someAsyncFunction, dependencies)` for `telefunc/react` and `useStateWithData()` for `vike-react`.

As for Solid, I ain't familiar with Solid, so I ain't sure what a nice API would be that aligns with my proposed naming for React.

**Comment by rtritto** [comment]
> ... `useStateWithData()` for `vike-react`.

IMO the name of `useData` hook is better (perfect) than `useStateWithData` one: set initial value in the `+data` hook (vike/server side) and then use the hook with `useData`.
Maybe you should only change the name `useData` if there is another `useData` method/keyword in the frontend frameworks.

> As for Solid, I ain't familiar with Solid, so I ain't sure what a nice API would be that aligns with my proposed naming for React

The implementation of `useData` is "hidden" because it doesn't depend by the frontend frameworks: `vike-react` uses _usePageContext_, `vike-react` uses store from _solid-js/store_ etc

**Comment by brillout** [comment]
The reason I like `useStateWithData()` is because it *does* define a state and the lifecycle is the as same `useState()`. It's basically `useState()` + data as initial value — why not giving it a name that describes what it does? The name is a lot more explicit than just `useData()`.

**Comment by rtritto** [comment]
> why not giving it a name that describes what it does?

Yes, this is another design choice to descibe the type (behavior, lifecycle) used in the implementation, you have to change as explicit each vike's hook and respect the related return type:
- `vike-react` → `useStateWithData`
- `vike-solid` → `useStoreWithData` (this feature request is needed to respect the store return type as getter and setter)

This choice is also good for me.

**Comment by brillout** [comment]
Yea, that's what I'm thinking.

In case you're up for it, contribution welcome for `vike-{react,vue,solid}`. (I'll do it for Telefunc once I'm done with my current priorities.)
