### ISSUE TITLE
vike-react-query: Linter error when using useSuspenseQuery() inside withCallback()

### ISSUE THREAD

**Issue by pjaydev** [vikejs/vike#2022]
### Description

When following the instructions in the `vike-react-query` [README](https://github.com/vikejs/vike-react/tree/main/packages/vike-react-query#withfallback) on how to use `withCallback()`, ESLint's *react-hooks/recommended* plugin (understandably) complains:

```
React Hook "useSuspenseQuery" cannot be called inside a callback. 
React Hooks must be called in a React function component or a custom React Hook function 
```

Of course, adding `/* eslint react-hooks/rules-of-hooks: 0 */ ` on top of the file will mute the linter here, but this is not an ideal solution.

Thank you for your great work on Vike!

**Comment by brillout** [comment]
Up for a PR?

**Comment by pjaydev** [comment]
Okay, I just realized, the linter can also be satisfied by outsourcing the inline component to a separate function:

```ts
const MovieWithoutFallback = ({ id }: { id: string }) => {
    const result = useSuspenseQuery({
        queryKey: ['movie', id],
        queryFn: () =>
            fetch(`https://brillout.github.io/star-wars/api/films/${id}.json`)
                .then((res) => res.json())
    })

    const { title } = result.data

    return (
        <div>
            Title: <b>{title}</b>
        </div>
    )
};

export const Movie = withFallback(
    MovieWithoutFallback,
    ({ id }) => <div>Loading movie {id}</div>,
    // The props `retry` and `error` are provided by vike-react-query
    // Other props, such as `code`, are provied by the parent component
    ({ id, retry, error }) => (
        <div>
            Failed to load movie {id}
            <button onClick={() => retry()}>Retry</button>
        </div>
    )
)
```

So this is indeed rather an ESLint-related issue, since it does not properly identify the inline component as a valid component but rather as a "callback". 

I don't know, if it would make sense to add a little note about this in the Readme, but I guess this is actually out of `vike-react-query`'s scope...

**Comment by brillout** [comment]
Hm, not sure, it does seem to be a user-land thing that is entirely independent from vike-react-query. Could happen with another library right?

**Comment by pjaydev** [comment]
@brillout yes, totally agree now. But thanks for your quick response!

Sorry for bringing that up in the first place.
