### ISSUE TITLE
The keepalive component cannot be used normally in vike

### ISSUE THREAD

**Issue by gortonlau** [vikejs/vike#2026]
### Description

I tried using keepalive to cache page data, but I couldn't do it. This should be a bug. I can provide an online example to reproduce the issue.

https://stackblitz.com/edit/zoksmojo?file=layouts%2FLayoutDefault.vue

**Comment by brillout** [comment]
Publish the repro on GitHub with a README describing your issue. I'll re-open then.

**Comment by gortonlau** [comment]
@brillout 

github repro
https://github.com/gortonlau/vike-vue

I introduced keepalive in /layouts/LayoutDefault.vue to ensure state persistence between pages. However, in my tests, it has not achieved the expected effect. The same code does not have this issue in a standalone Vue project. I named the page components using the name option and tested, but it still did not achieve the desired effect.

My expected outcome is that the state should be preserved after page navigation, rather than the data being lost. I am more familiar with traditional development like C++ and assembly, and not particularly experienced with front-end development. Please forgive my ignorance.

**Comment by brillout** [comment]
I wouldn't know how this can be related to Vike. I'm inclined to think it's either a Vue issue or a user-land issue (e.g. maybe wrapping a slot isn't supported). But I'm happy to continue the conversation if you find evidence that your issue is caused by Vike.
