### ISSUE TITLE
Error: [vike@0.4.171][Bug]

### ISSUE THREAD

**Issue by sharangahirekar-io** [vikejs/vike#2027]
### Description

createErrorWithCleanStackTrace.js?v=ce1c4888:4 Uncaught (in promise) Error: [vike@0.4.171][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. 
Got this error while passing props via pagecontext to client

**Comment by brillout** [comment]
Update to the latest version. I'll re-open if you still get this.
