### ISSUE TITLE
Link Prefetching: also prefetch `pageContext`

### ISSUE THREAD

**Issue by XiNiHa** [vikejs/vike#246]
Currently, there's no way to do any user-defined additional preloading jobs after finishing to preload static assets. So it's impossible to prefetch data needed for routes. Having an `onAfterPreload` hook (tried to match the naming convention) will solve the problem and it'll be very helpful to deeply tune the page performance.

**Comment by brillout** [comment]
My idea so far for this is to:
 1. Extend the `prefetchLink` option, e.g.:
    ```js
    useClientRouter({
      prefetchLinks: {
        when: 'ON_HOVER',
        what: ['STATIC_ASSETS', 'PAGE_CONTEXT']
      }
    })
    ```
 1. Allow the definition of a client-side-only `onBeforeRender()` (needed for tools such as Relay).

**Comment by XiNiHa** [comment]
I agree with you, that sounds very simple and straightforward.

**Comment by brillout** [comment]
With 0.4 the DX is quite straightforward:

```js
// /renderer/_default.page.client.js

export const prefetchStaticAssets = { when: 'VIEWPORT' }
export const prefetchPageContext = { when: 'HOVER', expire: 10 * 1000  }
```

Implementation should be fairly easy. But low priority since Vike/Stem is higher priority right now.

**Comment by archit-p** [comment]
Hi @brillout, is this part of the v1 design (#578) and being worked on? I'd love to work on it!

**Comment by brillout** [comment]
@archit-p It isn't but this feature can be implemented independently of the V1 design. PR welcome!

**Comment by usk94** [comment]
Hi, @brillout!
May I work on it?

**Comment by brillout** [comment]
Hi @usk94, yes!

**Comment by usk94** [comment]
@brillout 
Let me ask a question: 
should prefetchPageContext.when default to false?
Also, do I need to support override for individual links?

**Comment by brillout** [comment]
So far I'm inclined to think that we can enable it on `HOVER` by default. But let's see.

> Also, do I need to support override for individual links?

I think that would be nice? Or do you see an issue with that?

**Comment by usk94** [comment]
@brillout 
It's `HOVER` by default, OK🙆‍♂️

> Or do you see an issue with that?

I don't have at the moment. I just asked to be sure, thank you!

**Comment by loteoo** [comment]
Just sharing my interest in this issue :)

Two considerations:
- Is there a way to reuse some of the logic that is already in place for the loading of the page JS bundles?
- Would it make sense that, for static sites, it would only fetch the page context once per page? (keeps the data in memory, doesn't re-fetch it if it already has it?)

Loving vike for static sites! ❤️

**Comment by brillout** [comment]
I'm not sure I understand your first point. The second point makes a lot of sense, although it isn't the focus right now to make it perfect (the sponsor who requested this feature doesn't use SSG). Let's see.

**Comment by loteoo** [comment]
Sorry for the late reply, I guess my first point was just a reminder that there is already some logic in the vike codebase for this, and that it could potentially have been reused for this new feature to avoid logic duplication. (JS bundles already have the option to get prefetched on hover or viewport, and only get downloaded once per page, unlike the page context which will get re-downloaded every time you navigate to a page, even when the site is a static site)

**Comment by brillout** [comment]
Let's re-open because, while there is a rudimentary implementation, it isn't publicly available yet.

- Early experimental support: https://github.com/vikejs/vike/pull/1617

TODO (for Vike maintainers):
- Implement all `TO-DO/pageContext-prefetch`
- Add cache cleanup interval loop
