### ISSUE TITLE
Workaround wrongly published packages

### ISSUE THREAD

**Issue by brillout** [vikejs/vike#621]
### Description

Examples:
 - https://github.com/vitejs/vite/issues/11299
 - https://github.com/aws-amplify/amplify-ui/issues/3155
 - https://github.com/cyco130/vite-plugin-cjs-interop

**Comment by brillout** [comment]
- https://github.com/brillout/vite-plugin-ssr/discussions/635

**Comment by brillout** [comment]
https://github.com/vitejs/vite/issues/11299

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/682

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/700#discussioncomment-5283034

**Comment by brillout** [comment]
- Move all user land to ESM in order to avoid:
    ```
    Error [ERR_REQUIRE_ESM]: require() of ES Module
   /home/rom/code/vite-plugin-ssr/node_modules/.pnpm/node-fetch@3.3.1/node_modules/node-fetch/src/index.js
   from
   /home/rom/code/vite-plugin-ssr/examples/graphql-apollo-react/server/index.js
   not supported.
   ```

**Comment by brillout** [comment]
CSS imports: https://github.com/brillout/vite-plugin-ssr/discussions/791.

**Comment by brillout** [comment]
> CSS imports: #791.

Maybe, instead of automatically setting `ssr.noExternal`: and try-catch at `ssrLoadModule()` and tell user to add library to `ssr.noExternal`.

**Comment by brillout** [comment]
> > CSS imports: #791.
> 
> Maybe, instead of automatically setting `ssr.noExternal`: add try-catch at `ssrLoadModule()` and tell user to add library to `ssr.noExternal`.

Contribution welcome.

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/830

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/901

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/934

**Comment by brillout** [comment]
Also `ReferenceError: window is not defined`

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/571#discussioncomment-6137618 (including repro: https://github.com/antun/vite-ssr-redux-react-live-runner-example).

**Comment by brillout** [comment]
> add try-catch 

Actually, this also works for teaching users about hydration mismatches.

And React's infamous `Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`.

**Comment by brillout** [comment]
> And React's infamous `Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`.

Workaround for React's broken stack trace: https://github.com/brillout/vite-plugin-ssr/discussions/571#discussioncomment-6143928. Reprod: https://github.com/brillout/vite-plugin-ssr/discussions/571#discussioncomment-6144329.

**Comment by brillout** [comment]
https://github.com/brillout/vps-mui

**Comment by brillout** [comment]
Closing in favor of https://github.com/brillout/vite-plugin-ssr/issues/984. The new plan should be a lot simpler than the current workaround.

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/1021

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/1023#discussioncomment-6497430

**Comment by brillout** [comment]
Bun may come to the rescue: Bun's next release will work with Vite https://github.com/oven-sh/bun/issues/250#issuecomment-1643029102.

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/1031

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/1071#discussioncomment-6763419 (with reprod)

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-ssr/discussions/1084 (reprod requested)

**Comment by brillout** [comment]
List of wrongly published npm packages: see screenshot [here](https://github.com/vitejs/vite/issues/14158#issuecomment-1685052453).

**Comment by brillout** [comment]
List of wrongly published npm packages [here](https://github.com/brillout/vite-plugin-ssr/discussions/1080#discussioncomment-6806973).

**Comment by brillout** [comment]
`vue-toast-notification` ESM-CJS issue: https://github.com/brillout/vite-esm-cjs-reprod (with reprod)

**Comment by brillout** [comment]
Vue + Map library: https://github.com/vikejs/vike/discussions/1149 (reprod: https://github.com/brillout/vite-vue-cjs-esm-issue).

This one showcases an issue inside library code that the user cannot (easily) modify.

**Comment by brillout** [comment]
Vue + Primevue: https://github.com/vikejs/vike/discussions/1153#discussioncomment-7151333 (with reprod)

> Showcases that Vite inconsistently adds the library to `ssr.noExternal` only in dev.

> This one showcases an issue inside library code that the user cannot (easily) modify.

Same here.

**Comment by brillout** [comment]
- If a package that contains `__dirname` is `ssr.noExternal` => error is thrown at runtime.
  - `__dirname` cannot be shimmed for files that are bundled.
    - Ideally an error should be thrown while building. (Maybe with a feature that enables whitelisting npm packages that contain `__dirname` but that are still working when `ssr.noExternal`.)
  - https://github.com/vitejs/vite/discussions/9367

**Comment by AurelienLourot** [comment]
Preact+Redux+SSR:
* problem: #1235 
* reproducer: https://github.com/AurelienLourot/vike-preact-server-routing
* fix: https://github.com/JeffreyATW/vike-preact-server-routing/pull/1

**Comment by brillout** [comment]
Reprod: https://github.com/brillout/esm-cjs-issue_react-image-gallery

- `Following error was thrown by the onRenderHtml() hook defined at /renderer/+onRenderHtml.tsx
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`
- Failed attempt to use `ssr.optimizeDeps` (see https://github.com/vitejs/vite/issues/14158#issuecomment-1685033558).
- CJS npm package.
- `ssr.noExternal` doesn't work, while https://github.com/cyco130/vite-plugin-cjs-interop works.

**Comment by brillout** [comment]
Reprod: https://github.com/brillout/vike-lazyload-error-reproduction
 * CJS npm package.
 * `ssr.noExternal` doesn't work, while https://github.com/cyco130/vite-plugin-cjs-interop works.

**Comment by brillout** [comment]
React Native Web: https://github.com/vikejs/vike/discussions/1637. This is the only one I couldn't manage to quickly fix (but maybe it's fixable by digging into the hook rule issue). I could workaround the server-side tranpsilation issues, but it then fails at a React hook issue. Reprod: https://github.com/vikejs/vike/discussions/1637#discussioncomment-9424712.
