### ISSUE TITLE
Optional include/exclude pattern for faster page files crawl

### ISSUE THREAD

**Issue by bagr001** [vikejs/vike#818]
### Description

Hi,
I have noticed drastic slowdown of project startup time after I placed a "cache" folder in my project containing thousands of files.
I suggest adding optional include/exclude pattern for page files location to VPS configuration, which will increase crawling speed.

```ts
vps({
    pageFiles: {
        include: ['/pages/**/*'],
        // or
        exclude: ['/.cache/**/*'],
    }
});
```

Thanks!

**Comment by brillout** [comment]
Good idea. Let me implement this. ETA today.

**Comment by brillout** [comment]
Actually, while vite-plugin-ssr can implement this, this will require changes on Vite's side as well as Vite [currenty doesn't support such option](https://github.com/vitejs/vite/blob/07bd6d14e545d05c6a29cf341f117fcfe9536ba4/packages/vite/src/node/plugins/importMetaGlob.ts#L394-L402).


I could do a Vite PR. Although I usually do this kind of extra-mile work only for sponsors. I also believe it's a unique feature that other frameworks like Next.js don't support.

**Comment by brillout** [comment]
Actually, I think I'm mistaken: frameworks probably don't crawl the whole repository.

Let me know if this is a blocker for you and I'll have a second look at this.

**Comment by brillout** [comment]
A workaround is to create a hidden directory (i.e. a dir with a name that starts with `.`) and move the files you want to be skipped in there.

**Comment by brillout** [comment]
`fast-glob` (which both Vite and vite-plugin-ssr uses) ignores hidden dirs: https://github.com/mrmlnc/fast-glob#dot.

**Comment by brillout** [comment]
We could also automatically exclude the patterns defined by `.gitignore`.

I wonder whether that would cover most/(all?) uses cases.

@bagr001 @lookyman @tausa17 @Andrewsville @enri90 @stof66 @blagodus Would that work for you?

Let us know if you need more control, i.e. if a `type ConfigCrawl = { gitignore: boolean, exclude: string[], include: string[] }` is needed.

**Comment by bagr001** [comment]
Perfect! I thing excluding the patterns defined by `.gitignore` would cover most use cases.

Thanks!

**Comment by brillout** [comment]
> I thing excluding the patterns defined by `.gitignore` would cover most use cases.

Done by @nitedani in https://github.com/vikejs/vike/pull/1264.

Vike now uses `git ls-files` (thus `.gitignore` is applied) while falling back to `fast-glob` if Vike didn't find any `+` files with `git ls-files` (thus supporting users who generate the `+` files such as BurdaForward @ChristophP).

Make sure to ugrade to the V1 design (which is getting out of beta very soon): the old design still always uses `fast-glob`.
